### ISSUE TITLE
Commands not executing

### ISSUE THREAD

**Issue by gururise** [Josh-XT/Agent-LLM#105]
Running Locally with the following cfg:
AI_PROVIDER=openai
AI_MODEL=gpt-3.5-turbo
COMMANDS_ENABLED=True
WORKING_DIRECTORY=WORKSPACE

Given the objective: **Find the price of the nvidia 4090** 
The agent runs and generates [tasks](https://pastebin.com/mZ9XhHBt).

However, it seems like none of the commands ever run. No data is being pulled via google search, or browse website.  
**Task Result** is always empty.

The WORKSPACE directory is always empty.  And in the Agent directory, only the log file (linked above) is visible.

**Comment by Noyzax** [comment]
Have you implemented api key from openai?

**Comment by gururise** [comment]
> Have you implemented api key from openai?

Yes. Open api is being queried just fine, just no commands are being executed.

**Comment by Josh-XT** [comment]
I'll take a look at this tonight to see what is going on with it.

**Comment by Josh-XT** [comment]
https://github.com/Josh-XT/Agent-LLM/pull/111/files

Silly issue.  Give it another try. :)

**Comment by gururise** [comment]
submitted a PR to fix the regular expression matching. Was not matching on "COMMANDS:"

**Comment by Josh-XT** [comment]
Updated that line with your changes and committed to the main branch.  Give it another try when you have a chance.

**Comment by gururise** [comment]
The regular expression is now working and the commands are properly put into a list; however, on line [99](https://github.com/Josh-XT/Agent-LLM/blob/0648f745f3e2081cf40804a4d936fbcbc705f22e/AgentLLM.py#L99), when the arguments are parsed into a dictionary, a failure occurs.

args_str = "{'filename': 'AI_info.txt', 'memory': 'AI_info', 'max_length': 4000, 'overlap': 200}"

```
Exception has occurred: ValueError
not enough values to unpack (expected 2, got 1)
  File "/home/gene/Downloads/Agent-LLM/AgentLLM.py", line 99, in <genexpr>
    command_args = dict((key.strip(), value.strip()) for key, value in (arg.split('=') for arg in args_str.split(',')))
  File "/home/gene/Downloads/Agent-LLM/AgentLLM.py", line 99, in run
    command_args = dict((key.strip(), value.strip()) for key, value in (arg.split('=') for arg in args_str.split(',')))
  File "/home/gene/Downloads/Agent-LLM/AgentLLM.py", line 222, in execution_agent
    return self.run(prompt)
  File "/home/gene/Downloads/Agent-LLM/AgentLLM.py", line 235, in run_task
    result = self.execution_agent(task["task_name"], task["task_id"])
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by gururise** [comment]
So there are actually **two problems:**

1. Sometimes the LLM will respond with the following command list:
```
Read File - read_file({'filename': 'previous_tweets.txt'})
Ingest File - ingest_file({'filename': 'previous_tweets.txt', 'memory': 'previous_tweets', 'max_length': 4000, 'overlap': 200})
Create Message - create_message({'chunk': 'AI is transforming the way we live and work.', 'question': 'What do you think about this idea for an AI tweet?'})
Check Duplicate Operation - check_duplicate_operation({'operation': 'send_tweet()', 'filename': 'previous_tweets.txt'})
Send Tweet - send_tweet({'text': 'AI is transforming the way we live and work. #AI #future'})
```
Notice how the actual command is preceded by a title (ie. Read File, Ingest File, Create Message, etc.).  When this happens, the regex on [94](https://github.com/Josh-XT/Agent-LLM/blob/0648f745f3e2081cf40804a4d936fbcbc705f22e/AgentLLM.py#L94) fails to extract the actual command.

2. The second problem is listed above, with the parsing of the arguments into a dictionary.

**Comment by Josh-XT** [comment]
> 

Thanks!  I imagine we'll need to play with this a little more over time to handle how other models might respond.

**Comment by Josh-XT** [comment]
> Just found another issue with ChatGPT and gpt-3.5-turbo.
> 
> Sometimes, the LLM will respond with COMMANDS and forget to put the arguments in a DICT like so:
> 
> ```
> ingest_file('file.txt', 'mem1', 4000, 200) - to save important information to memory.
> read_file('mem1') - to recall past events and information.
> browse_website('https://www.google.com/', 'What are some recent developments in AI?') - to research recent developments in AI.
> browse_website('https://www.twitter.com/', 'What are some popular opinions on AI in the media?') - to research popular opinions on AI in the media.
> create_message('AI is changing the world with its advancements. #AI #technology') - to create a rough draft of the tweet.
> send_tweet() - to post the tweet.
> ```

I may be able to improve this through prompting.
