### ISSUE TITLE
Detail Not Found When Building Task List

### ISSUE THREAD

**Issue by timuryunuk2023** [Josh-XT/Agent-LLM#106]
Executing task 1: Develop a task list.

INFO:     127.0.0.1:49426 - "GET /api/agent/undefined/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:49428 - "GET /api/agent HTTP/1.1" 200 OK
INFO:     127.0.0.1:49430 - "GET /api/agent/Agent-LLM HTTP/1.1" 200 OK
INFO:     127.0.0.1:49432 - "GET /api/agent/Agent-LLM/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:49434 - "POST /api/agent/Agent-LLM/task HTTP/1.1" 200 OK
INFO:     127.0.0.1:49424 - "GET /api/agent/Agent-LLM/task/status HTTP/1.1" 200 OK
Response: {'detail': 'Not Found'}

Task Result:

{'detail': 'Not Found'}

Response: {'detail': 'Not Found'}

New Tasks:

[{'task_name': {'detail': 'Not Found'}}]

Exception in thread Thread-2 (run_task):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/timur/Downloads/Agent-LLM-1.1.0/AgentLLM.py", line 242, in run_task
    self.prioritization_agent()
  File "/Users/timur/Downloads/Agent-LLM-1.1.0/AgentLLM.py", line 196, in prioritization_agent
    prompt = prompt.replace("{task_names}", ", ".join(task_names))
                                            ^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, dict found

When try to execute task
Starting task with objective: Research about pizza and save your findings in the text file.

Executing task 1: {'detail': 'Not Found'}

INFO:     127.0.0.1:49448 - "POST /api/agent/Agent-LLM/task HTTP/1.1" 200 OK
Exception in thread Thread-3 (run_task):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/timur/Downloads/Agent-LLM-1.1.0/AgentLLM.py", line 235, in run_task
    result = self.execution_agent(task["task_name"], task["task_id"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Downloads/Agent-LLM-1.1.0/AgentLLM.py", line 213, in execution_agent
    prompt = prompt.replace("{task}", task)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: replace() argument 2 must be str, not dict

Objective Work Log
Starting task with objective: Research about pizza and save your findings in the text file.
Executing task 1: Develop a task list.
Task Result:
{'detail': 'Not Found'}
New Tasks:
[{'task_name': {'detail': 'Not Found'}}]
Starting task with objective: Research about pizza and save your findings in the text file.
Executing task 1: {'detail': 'Not Found'}

after applying fix from @gururise this error still occurs
Objective Work Log
Starting task with objective: Research about pizza and save your findings in the text file.
Executing task 1: Develop a task list.
Task Result:
{'detail': 'Not Found'}
New Tasks:
[{'task_name': {'detail': 'Not Found'}}]
Starting task with objective: Research about pizza and save your findings in the text file.
Executing task 1: {'detail': 'Not Found'}
Starting task with objective: Research about pizza and save your findings in the text file.
Executing task 1: Develop a task list.
Task Result:
None
Starting task with objective: Research about pizza and save your findings in the text file.
Executing task 1: Develop a task list.
Task Result:
None
Starting task with objective: Research about pizza and save your findings in the text file.
Executing task 1: Develop a task list.

Environment
Mac os 10.13
Running locally without docker

**Comment by gururise** [comment]
what model are you running in oobabooga?

**Comment by gururise** [comment]
Almost certain this is a limitation of the local model not being able to properly handle the prompt.

**Comment by Josh-XT** [comment]
I believe you got this sorted talking in discord with us.  Let me know if still having the issue.
