### ISSUE TITLE
Unclear .env Configuration Instructions

### ISSUE THREAD

**Issue by linuxreitt** [Josh-XT/Agent-LLM#131]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](./CODE_OF_CONDUCT.md)

### What article is affected?

It would be great to have some clear up to date instructions on configuring the .env file. I have been trying to configure for use with llama.cpp, 7B/ggml-model-f16.bin for some time without success, web UI errors include 404 and  Error! Network Error. I don't know if my MODEL_PATH is the issue or AI_PROVIDER/AI_MODEL. Agent-LLM sounds absolutely fantastic, if only I could get it working.

### What part(s) of the article would you like to see updated?

Setup/User Guide

**Comment by JamesonRGrieve** [comment]
You're pointing at the correct file.

Here's mine for reference. `MODEL_PATH=G:/llm/Agent-LLM/models/alpaca-7b/ggml-model-q4_1.bin`

**Comment by Josh-XT** [comment]
Hello!  I've updated the documentation for this to be a little clearer.

https://github.com/Josh-XT/Agent-LLM/blob/main/docs/providers/LLAMACPP.md

Please let us know if it is still an issue.
