### ISSUE TITLE
Left Sub-Menu Transition Slides Over Main Menu

### ISSUE THREAD

**Issue by JamesonRGrieve** [Josh-XT/Agent-LLM#132]
### Title

Left Sub-Menu Transition Slides Over Main Menu

### Description

When opening the left sub-menu on any enabled page with the main menu open, the sub-menu slides overtop of the main menu.

### Steps to Reproduce

1. Open any page with a left sub-menu.
2. Open the main menu.
3. Open the left sub-menu.

### Expected Behavior

Basis of sub-menu should be the right edge of the main menu, so if closed it originates from the left side of the screen and if open it originates from the right side of the menu.

### Actual Behavior

Sub-menu slides over-top of main menu.
![image](https://user-images.githubusercontent.com/37882431/234747002-c2c5fcb8-d166-4a9e-813e-2f574210a2e5.png)

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet
- [X] I am using the latest version of the software
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue

**Comment by Josh-XT** [comment]
https://github.com/JamesonRGrieve/Agent-LLM-Frontend

Please direct front end issues to the front end repository.
