### ISSUE TITLE
No commands executing

### ISSUE THREAD

**Issue by Captain-Bacon** [Josh-XT/Agent-LLM#133]
### Title

Commands not executing

### Description

No commands are being executed, of any description.

Example output:

Starting task with objective: write a text file with the words 'hello world' as the contents.  do not do anything else..
Executing task 28: Use the "write_to_file" command to write the word "hello" to a file named "hello.txt".
All tasks completed or stopped.
Task Result:
THOUGHTS: This task is straightforward and can be easily accomplished with the "write_to_file" command.
REASONING: The "write_to_file" command is designed to write text to a file, which is exactly what we need to do to complete this task.
PLAN:
1. Use the "write_to_file" command to write the word "hello" to a file named "hello.txt".
COMMANDS:
False
New Tasks:
[{'task_name': '1. Use the "write_to_file" command to write the words "hello world" to a file named "hello.txt".'}, {'task_name': '2. Celebrate the successful completion of the task with the team!'}]
Executing task #31: Ensure that all necessary libraries and tools are installed and up-to-date.
Task Result:
THOUGHTS: This task seems straightforward and simple.
REASONING: Installing and updating necessary libraries and tools is an important step in ensuring that the AI can perform its tasks efficiently and effectively.
PLAN: 
1. Check if necessary libraries and tools are already installed.
2. If not, install them.
3. Check if the installed libraries and tools are up-to-date.
4. If not, update them.
COMMANDS:
False
False
False
False
False
False
Command not recognized: 
Command not recognized: CRITICISM: None.
New Tasks:
[{'task_name': '1. Check if "write_to_file" command is available.'}, {'task_name': '2. If not, install necessary libraries and tools.'}, {'task_name': '3. Check if "hello.txt" file already exists.'}, {'task_name': '4. If not, create "hello.txt" file.'}, {'task_name': '5. Write the words "hello world" to "hello.txt" file using "write_to_file" command.'}, {'task_name': '6. Check if all incomplete tasks have been completed.'}, {'task_name': '7. If yes, celebrate the successful completion of the task with the team!'}]
Executing task 10: Check if "write_to_file" command is available.
Task Result:
THOUGHTS: This task is straightforward and can be easily accomplished with the "write_to_file" command.
REASONING: The "write_to_file" command is specifically designed for writing text to a file, so it is the most appropriate command to use for this task.
PLAN: Use the "write_to_file" command with the filename "hello_world.txt" and the text "hello world" to write the desired contents to a file.
COMMANDS:
False

### Steps to Reproduce

Set agent objective to "write a text file with the words 'hello world' as the contents.  do not do anything else."

### Expected Behavior

It would complete a command

### Actual Behavior

It, er, doesn't.

### Additional Context

I am using the 'Mac' version inside Docker.

FYI, the prompts and chains functions are not available either - they're greyed out.  And it's trying to reference a bad path to get the 'Prompt' heading.

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [X] Python 3.11

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet
- [X] I am using the latest version of the software
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue

**Comment by CRCODE22** [comment]
I have the same errors with llamacpp and a flood of them reducing to just one here in the comment section of each:

When using obabagoo however there are no results at all and no errors it just keeps using 100% gpu or almost full load of processor even after 40 minutes no results tested with multiple models.

I tried several models
COMMANDS:
False
Command not recognized:
Command not recognized: CRITICISM: None.

**Comment by Captain-Bacon** [comment]
yeah, I don't have any of those options to try - everything's greyed out...

<img width="1137" alt="Screenshot 2023-04-27 at 11 45 11" src="https://user-images.githubusercontent.com/123217107/234840056-9257abb1-b073-4ee5-b7ff-c30291decda6.png">
<img width="999" alt="Screenshot 2023-04-27 at 11 45 07" src="https://user-images.githubusercontent.com/123217107/234840083-ba917e45-2220-4a3e-b7bc-75a623095b56.png">
<img width="1171" alt="Screenshot 2023-04-27 at 11 45 01" src="https://user-images.githubusercontent.com/123217107/234840112-0db467e7-2b0a-402c-92b1-d2aefc3f832f.png">

**Comment by Copterz** [comment]
All my options are greyed out as well using oobabooga same as the post above

**Comment by Josh-XT** [comment]
Hello.  Please update to the latest version.  We have done a lot of bug fixing in the past couple of days.

https://github.com/Josh-XT/Agent-LLM/releases/tag/v1.0.16-alpha

The prompts, chains, and providers pages are all placeholders.  We're still building out the front end functionality for those.
