### ISSUE TITLE
Massive Badges on Front End

### ISSUE THREAD

**Issue by JamesonRGrieve** [Josh-XT/Agent-LLM#136]
### Title

Massive Badges on Front End

### Description

Self explanatory.

### Steps to Reproduce

Load the front end.

### Expected Behavior

Badges should be rendered as in the GitHub page.

### Actual Behavior

![image](https://user-images.githubusercontent.com/37882431/234751204-64366895-6a60-4d4b-9abc-f76dcba49df7.png)

### Additional Context

There's a global CSS rule for `img` to be `width: 100%` for screenshots. It just needs to be made a little more specific.

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet
- [X] I am using the latest version of the software
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue

**Comment by Josh-XT** [comment]
#145 should have this fixed.
