### ISSUE TITLE
Vague Error Messages When No Server Communication

### ISSUE THREAD

**Issue by JamesonRGrieve** [Josh-XT/Agent-LLM#137]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](./CODE_OF_CONDUCT.md)

### What article is affected?

Front end menus.

### What part(s) of the article would you like to see updated?

The "Network Error" should be replaced with smaller font with the verbose error message.

![image](https://user-images.githubusercontent.com/37882431/234751524-5c985517-7999-49f6-9ea4-18ecd2d52437.png)

**Comment by JamesonRGrieve** [comment]
This appears to be an Axios issue. Best workaround is to check for "Network Error" and elaborate IE "Communication error. Is the server running? Are the ports defined correctly?"

**Comment by Josh-XT** [comment]
A lot of changes were done over the past week in the branch that we just merged for v1.1.0-alpha.  Please try it and create an issue if ongoing.
