### ISSUE TITLE
front end problem, it is asking for the commands from the wrong endpoint

### ISSUE THREAD

**Issue by CRCODE22** [Josh-XT/Agent-LLM#142]
### Description

JoshXT
 — 
Today at 5:42 PM
it is a front end problem, it is asking for the commands from the wrong endpoint
check if there is an issue in github and make one if not please, I'll need James to see why it isn't hitting the right endpoint

All commands are disabled in gui and even config.json with the exception of "Get Datetime - get_datetime({})" of the agent but still all commands are visible to the model it should only allow Get Datetime - get_datetime({}) to be seen.

You have the following commands available to complete this task given.
Get Datetime - get_datetime({})
Is Valid URL - is_valid_url({'url': None})
Sanitize URL - sanitize_url({'url': None})
Check Local File Access - check_local_file_access({'url': None})
Get Response - get_response({'url': None, 'timeout': 10})
Scrape Text - scrape_text({'url': None})
Scrape Links - scrape_links({'url': None})
Create Message - create_message({'chunk': None, 'question': None})

I moved the rest of the commands from the commands folder but one was mandatory and it is including all the commands above. it should only show "Get Datetime - get_datetime({})" as I disabled the rest

![image](https://user-images.githubusercontent.com/88407346/234917098-b33391f1-e4f9-4875-b291-e7124ec711bc.png)
![image](https://user-images.githubusercontent.com/88407346/234917178-2a8cd970-1bc8-43b7-9a20-63b660cdce04.png)

### Steps to Reproduce the Bug

Disable all commands in the gui with exception of getdatetime
instruct agent with the following prompt:Get the date and time from my computer and let me know
Click instruct.

### Expected Behavior

To have all commands disabled with the exception of Get Datetime - get_datetime({})

### Actual Behavior

It is passing all commands to the model even tough they are all disabled in the gui and config.json with the exception of Datetime - get_datetime({}) that one it is allowed to use.

### Additional Context / Screenshots

NFO:     127.0.0.1:53498 - "POST /api/agent/Agent-LLM/instruct HTTP/1.1" 200 OK
INFO:     127.0.0.1:53506 - "GET /api/agent/undefined/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:53507 - "GET /api/agent HTTP/1.1" 200 OK
INFO:     127.0.0.1:53508 - "GET /api/agent/Agent-LLM HTTP/1.1" 200 OK
INFO:     127.0.0.1:53509 - "GET /api/agent/Agent-LLM/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:53547 - "GET /api/agent/undefined/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:53548 - "GET /api/agent HTTP/1.1" 200 OK
INFO:     127.0.0.1:53549 - "GET /api/agent/Agent-LLM HTTP/1.1" 200 OK
INFO:     127.0.0.1:53550 - "GET /api/agent/Agent-LLM/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:53557 - "GET /api/agent/undefined/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:53558 - "GET /api/agent HTTP/1.1" 200 OK
INFO:     127.0.0.1:53559 - "GET /api/agent/Agent-LLM HTTP/1.1" 200 OK
INFO:     127.0.0.1:53560 - "GET /api/agent/Agent-LLM/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:53561 - "GET /api/agent/undefined/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:53562 - "GET /api/agent HTTP/1.1" 200 OK
INFO:     127.0.0.1:53563 - "GET /api/agent/Agent-LLM HTTP/1.1" 200 OK
INFO:     127.0.0.1:53564 - "GET /api/agent/Agent-LLM/command HTTP/1.1" 200 OK

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by r1di** [comment]
I'm having the same issues, the agent is sending its commands to ChatGPT instead of executing them.

I'm running it locally, not in dockers btw.


```
You are an AI who performs one task based on the following objective: Create a flappy bird game, where the bird is replaced with a robot..
Your role is to do anything asked of you with precision. You have the following constraints:
1. ~4000 word limit for short term memory. Your short term memory is short, so immediately save important information to files.
2. If you are unsure how you previously did something or want to recall past events, thinking about similar events will help you remember.
3. No user assistance.

Take into account these previously completed tasks: .
Your task: 

You have the following commands available to complete this task.
Read Audio from File - read_audio_from_file({'audio_path': None})
Read Audio - read_audio({'audio': None})
Evaluate Code - evaluate_code({'code': None})
Analyze Pull Request - analyze_pull_request({'pr_url': None})
Perform Automated Testing - perform_automated_testing({'test_url': None})
Run CI-CD Pipeline - run_ci_cd_pipeline({'repo_url': None})
Improve Code - improve_code({'suggestions': None, 'code': None})
Write Tests - write_tests({'code': None, 'focus': None})
Create a new command - create_command({'function_description': None})
Execute Python File - execute_python_file({'file': None})
Execute Shell - execute_shell({'command_line': None})
Check Duplicate Operation - check_duplicate_operation({'operation': None, 'filename': None})
Log Operation - log_operation({'operation': None, 'filename': None})
Read File - read_file({'filename': None})
Ingest File - ingest_file({'filename': None, 'memory': None, 'max_length': 4000, 'overlap': 200})
Write to File - write_to_file({'filename': None, 'text': None})
Append to File - append_to_file({'filename': None, 'text': None})
Delete File - delete_file({'filename': None})
Search Files - search_files({'directory': None})
Google Search - google_search({'query': None, 'num_results': 8})
Google Official Search - google_official_search({'query': None, 'num_results': 8})
Generate Image - generate_image({'prompt': None})
Searx Search - search_searx({'query': None, 'category': 'general'})
Get Datetime - get_datetime({})
Send Tweet - send_tweet({})
Speak with TTS - speak({'text': None, 'engine': 'gtts', 'voice_index': 0})
Scrape Text with Playwright - scrape_text({'url': None})
Scrape Links with Playwright - scrape_links({'url': None})
Is Valid URL - is_valid_url({'url': None})
Sanitize URL - sanitize_url({'url': None})
Check Local File Access - check_local_file_access({'url': None})
Get Response - get_response({'url': None, 'timeout': 10})
Scrape Text - scrape_text({'url': None})
Scrape Links - scrape_links({'url': None})
Create Message - create_message({'chunk': None, 'question': None})
Browse Website - browse_website({'url': None, 'question': None})
Ask AI Agent Agent-LLM - ask({'prompt': None})
Instruct AI Agent Agent-LLM - instruct({'prompt': None})
Ask AI Agent CodingGPT - ask({'prompt': None})
Instruct AI Agent CodingGPT - instruct({'prompt': None})

FORMAT RESPONSES IN THE FOLLOWING FORMAT:

THOUGHTS: Your thoughts on completing the task.

REASONING: The reasoning behind your responses.

PLAN: Your plan for achieving the task.

CRITICISM: Your critism of the thoughts, reasoning, and plan.

COMMANDS: If you choose to use any commands, list them and their inputs where necessary.  List the commands in the order that they need to be executed with the format being command_name(args). Do not explain, just list the command_name(args).
```

**Comment by Josh-XT** [comment]
Hello.  We've done some bug fixes on the front end today, can you test and see if you're still having issues?
