### ISSUE TITLE
HuggingChat does not work

### ISSUE THREAD

**Issue by timuryunuk2023** [Josh-XT/Agent-LLM#152]
### Description

When I click start purshing objective button this error pops up
Exception in thread Thread-3 (run_task):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/timur/Downloads/Agent-LLM-1.0.15/AgentLLM.py", line 325, in run_task
    result = self.execution_agent(task["task_name"], task["task_id"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Downloads/Agent-LLM-1.0.15/AgentLLM.py", line 308, in execution_agent
    return self.run(prompt)
           ^^^^^^^^^^^^^^^^
  File "/Users/timur/Downloads/Agent-LLM-1.0.15/AgentLLM.py", line 119, in run
    self.response = self.instruct(prompt)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Downloads/Agent-LLM-1.0.15/provider/huggingchat.py", line 42, in instruct
    assert res.status_code == 200, "Failed to send message"
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Failed to send message

### Steps to Reproduce the Bug

1. Select the agent
2. Give it task
3. Press Start Purshing Objective button

### Expected Behavior

Starts execution of the task

### Actual Behavior

Gives error

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [ ] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Your prompt might be too big.  It has a 2048 max.

**Comment by Josh-XT** [comment]
![image](https://user-images.githubusercontent.com/102809327/235178880-acbb794a-4ca6-47ad-b956-e631d906c9f2.png)

**Comment by timuryunuk2023** [comment]
My prompt is "Research about pizza and save collected information in the text file"

**Comment by Josh-XT** [comment]
> I tried "Write a tweet about AI" prompt but I still get this error

It is the API response you're getting from Huggingchat.  So far the only times I am getting that is if I go over their max tokens.  Are you able to get to their website and use it? https://huggingface.co/chat/

**Comment by timuryunuk2023** [comment]
<img width="1437" alt="Знімок екрана 2023-04-28 о 18 56 31" src="https://user-images.githubusercontent.com/90114599/235219662-0426c3b9-ec78-4338-bb0b-99bf0653228c.png">
Yes, I could go and use it

**Comment by Josh-XT** [comment]
Try to create a new agent then try hugging chat.
