### ISSUE TITLE
Fix discord invite badge

### ISSUE THREAD

**Issue by MartyLake** [Josh-XT/Agent-LLM#156]
### What piece of documentation is affected?

Discord invite badge is invalid.

### What part(s) of the article would you like to see updated?

All the discord bagdes

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by Josh-XT** [comment]
If you're having an issue in discord, please let us know in discord.

> ### What piece of documentation is affected?
> Discord invite badge is invalid.
> 
> ### What part(s) of the article would you like to see updated?
> All the discord bagdes
> 
> ### Additional Information
> _No response_
> 
> ### Acknowledgements
> * [x]  My issue title is concise, descriptive, and in title casing.
> * [x]  I have searched the existing issues to make sure this feature has not been requested yet.
> * [x]  I have provided enough information for the maintainers to understand and evaluate this request.

Thanks for letting me know!  Just updated the link.

https://discord.gg/d3TkHRZcjD
