### ISSUE TITLE
Failed so send message error

### ISSUE THREAD

**Issue by timuryunuk2023** [Josh-XT/Agent-LLM#158]
### Description

I have start objective using Hugging face and got this error
![image](https://user-images.githubusercontent.com/90114599/235231889-a2103663-d86b-4c56-834e-38e36581e8ae.png)
at the same time test request passes OK
![image](https://user-images.githubusercontent.com/90114599/235231948-f3867f1d-15dd-4529-b0a4-133595fc1ff2.png)

### Steps to Reproduce the Bug

1. Create .env file with huggingface as AI provider
2. Start backend
3. Start frontend
4. Set agent objective

### Expected Behavior

Start the task execution

### Actual Behavior

Gives "Failed to send message" error

### Operating System

- [ ] Microsoft Windows
- [X] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [X] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Updated #162 to fix this.
