### ISSUE TITLE
No docker guide

### ISSUE THREAD

**Issue by Mandraw** [Josh-XT/Agent-LLM#179]
### What piece of documentation is affected?

The install guide

### What part(s) of the article would you like to see updated?

Would love to have a way to run this in a environement that doesn't have access to virtualization

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by Josh-XT** [comment]
https://github.com/Josh-XT/Agent-LLM/blob/main/docs/providers/OPENAI.md

Ask and you shall receive.

**Comment by Mandraw** [comment]
Mmmh I might be just stupid, but isn't the doc you shared use docker ?
