### ISSUE TITLE
Error Running Frontend Locally

### ISSUE THREAD

**Issue by VRImage** [Josh-XT/Agent-LLM#181]
### Description

When running frontend locally (npm run dev) the following error occurs:

```
/home/garlen/Agent-LLM/frontend/node_modules/next/dist/cli/next-dev.js:255
            showAll: args["--show-all"] ?? false,
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.dev (/home/garlen/Agent-LLM/frontend/node_modules/next/dist/lib/commands.js:10:30)
    at Object.<anonymous> (/home/garlen/Agent-LLM/frontend/node_modules/next/dist/bin/next:141:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR! code 1
npm ERR! path /home/garlen/Agent-LLM/frontend
npm ERR! command failed
npm ERR! command sh -c next dev

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/garlen/.npm/_logs/2023-05-01T11_27_58_838Z-debug.log
```

Running in wsl with a fresh clone

### Steps to Reproduce the Bug

```
git clone https://github.com/Josh-XT/Agent-LLM.git
cd Agent-LLM
pip install -r requirements.txt

cd frontend
npm install
npm run dev
```

### Expected Behavior

Run the frontend.

### Actual Behavior

Above mentioned error.

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [X] Other

### Python Version

- [X] Python <= 3.9
- [ ] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Please delete your `node_modules` folder inside of your `frontend` folder then try to run `npm install` again.

**Comment by VRImage** [comment]
Same error.
`npm install` generates a few warnings. Could that be an issue:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eslint-import-resolver-typescript@3.5.5',
npm WARN EBADENGINE   required: { node: '^14.18.0 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'next@13.3.0',
npm WARN EBADENGINE   required: { node: '>=14.6.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'synckit@0.8.5',
npm WARN EBADENGINE   required: { node: '^14.18.0 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
```

**Comment by Josh-XT** [comment]
Try also deleting your package lock file and then try `npm install` again.

We also updated to v1.1.0-alpha today.  Please update to the latest version and try.

**Comment by VRImage** [comment]
After updating node.js to version 16 it worked.
