### ISSUE TITLE
Consider opening github discussions or a project discord to provide a place for users to discuss and seek basic support.

### ISSUE THREAD

**Issue by Electrofried** [Josh-XT/Agent-LLM#19]
Might be a good idea to open discussions up as a place to discuss the project and make recommendations or help out others with basic issues. I have a feeling this project might blow up in popularity soon due to the low entry bar and fantastic implementation. Best to get ahead of the crowd and provide a place for these discussions before the issues page gets cluttered with "Why does x/y/z happen?" style posts.

The other option would be to start a community discord (honestly my preferred option). It is a great platform for projects like this. I would be happy to help out on discord in any way if that is the route you choose.

**Comment by OverwriteDev** [comment]
This would be great.

**Comment by Josh-XT** [comment]
I did make a discord if anyone is interested, haven't done much with it yet.
https://discord.gg/u5pGSpAT

I'll have to see how you set up the GitHub discussions, I haven't used that. Happy to chat and test in discord for sure.

**Comment by Electrofried** [comment]
Perfect! Discord is great. Just need to add the invite link to the main project page so people know to head there!
