### ISSUE TITLE
Add Agent Provider Settings to Add Agent page

### ISSUE THREAD

**Issue by Josh-XT** [Josh-XT/Agent-LLM#195]
### Problem Description

Confusing to people to add the agent by only entering the name then needing to go to the "Configure Agent" page to finish setting it up.  

### Proposed Solution

Need to duplicate what is on the configure agent screen on setup.

### Alternatives Considered

Alternatively, after adding an agent, we can route them to the configure agent screen next instead of to chat.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by lgwacker** [comment]
Guess jamie boy already fixed this one. Its redirecting to configure agent
