### ISSUE TITLE
Error when executing Task Agent

### ISSUE THREAD

**Issue by Copterz** [Josh-XT/Agent-LLM#197]
### Description

I used the following for the task: Write an engaging tweet about AI. It is communicating with my oobabooga api and tokens are being generated. After so many steps in it failed. May be related to the command button issue #186 as it seems to be looking for audio and the first command in the list is load audio from file, but really that is just pure speculation on my part as I have no idea what audio.mp3 is.

### Steps to Reproduce the Bug

1. Go to task agent
2. Type: Write an engaging tweet about AI.
3. Click "Start Pursuing Task"

### Expected Behavior

Task executes successfully

### Actual Behavior

EXECUTION: The steps you took to execute your plan.

RESULT: What happened as a result of your execution?

Response:

New Tasks:

[{'task_name': ''}]

Response:
Please write in English (US) language.

Executing task Please write in English (US) language:

Exception in thread Thread-6 (run_task):
Traceback (most recent call last):
  File "E:\AI\TCHT\oobabooga_windows\installer_files\env\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "E:\AI\TCHT\oobabooga_windows\installer_files\env\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\AI\TCHT\oobabooga_windows\Agent-LLM\AgentLLM.py", line 330, in run_task
    result = self.execution_agent(task["task_name"], task["task_id"])
  File "E:\AI\TCHT\oobabooga_windows\Agent-LLM\AgentLLM.py", line 313, in execution_agent
    return self.run(prompt)
  File "E:\AI\TCHT\oobabooga_windows\Agent-LLM\AgentLLM.py", line 158, in run
    f"\n\n{self.commands.execute_command(command_name, command_args)}"
  File "E:\AI\TCHT\oobabooga_windows\Agent-LLM\Commands.py", line 110, in execute_command
    output = command_function(module, **params)
  File "E:\AI\TCHT\oobabooga_windows\Agent-LLM\commands\audio_text.py", line 20, in read_audio_from_file
    with open(audio_path, "rb") as audio_file:
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/audio.mp3'

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
It appears to have hallucinated `/path/to/audio.mp3`, which doesn't exist.
