### ISSUE TITLE
ModuleNotFoundError: No module named 'playsound' after running python main.py

### ISSUE THREAD

**Issue by InfernalDread** [Josh-XT/Agent-LLM#2]
I have attempted to use pip3 install playsound, but that didn't work, so I do not know what to do next.

EDIT: The error came from voice.py in the commands folder.

**Comment by Josh-XT** [comment]
If you're using conda, you might have to do `conda install playsound` also.

**Comment by InfernalDread** [comment]
> If you're using conda, you might have to do `conda install playsound` also.

oh, I am using venv, should I be using conda instead?

**Comment by Josh-XT** [comment]
It should work either way.  I am running 3.10.9 with it.

**Comment by Josh-XT** [comment]
May also want to try `pip install -r requirements.txt` if you haven't yet.

**Comment by InfernalDread** [comment]
interesting, I am running 3.10.6, but I get an error everytime I use: pip3 install playsound or just pip install playsound.

I will try conda as well.

Also, I have installed the requirements.txt

**Comment by Josh-XT** [comment]
What OS are you on?  I haven't tested this on Windows at all.  Only in Ubuntu.  You may also have better luck trying to run with `docker-compose up -d`.  Web interface is severely lacking right now but it works.  Front end is next up.

**Comment by InfernalDread** [comment]
oh that makes more sense, I am using windows. I can try docker, but will that work on windows?

**Comment by InfernalDread** [comment]
oh, it looks like I was able to install playsound from source. lets see if this works

**Comment by Josh-XT** [comment]
> oh that makes more sense, I am using windows. I can try docker, but will that work on windows?

Yeah, that is the beauty of docker, it works pretty much anywhere.

**Comment by Josh-XT** [comment]
> oh, it looks like I was able to install playsound from source. lets see if this works

All good?

**Comment by InfernalDread** [comment]
I just finished a run (took a while cause PC isn't as good as it use to be), but when I ran the "npm start" command and put in an objective and clicked start babyagi, I just got a "404" code on the app.py screen. I was using oobabooga and vicuna and everything connected, but the babyagi wouldn't run. I also tried to install via docker, but the docker couldn't fully build on my PC for some reason. Maybe windows compatibly isn't for this repo lol.

**Comment by Josh-XT** [comment]
I spent a lot of time playing with babyagi and adapting it which ended up with this much larger adaptation, so I made my own repo for it today after getting some of the big functionality in place. It will have Windows support too, I've just been more into the development than the testing, which will continue to be the case. There will likely be windows contributors anyway. Front end is very much a work in progress as is the rest of the project, but the back end should work.

**Comment by InfernalDread** [comment]
> I spent a lot of time playing with babyagi and adapting it which ended up with this much larger adaptation, so I made my own repo for it today after getting some of the big functionality in place. It will have Windows support too, I've just been more into the development than the testing, which will continue to be the case. There will likely be windows contributors anyway. Front end is very much a work in progress as is the rest of the project, but the back end should work.

This is a major win in terms of local development for getting something like babyagi or auto gpt. I really appreciate all the work you put into this! All that's needed now is time like you said. I can't wait for what the future will bring. I will continue to monitor this repo and hopefully there will be a massive community for locally running these types of programs. Take your time, massive progress is being made.

Once again, massive thank you!

**Comment by Josh-XT** [comment]
> > I spent a lot of time playing with babyagi and adapting it which ended up with this much larger adaptation, so I made my own repo for it today after getting some of the big functionality in place. It will have Windows support too, I've just been more into the development than the testing, which will continue to be the case. There will likely be windows contributors anyway. Front end is very much a work in progress as is the rest of the project, but the back end should work.
> 
> This is a major win in terms of local development for getting something like babyagi or auto gpt. I really appreciate all the work you put into this! All that's needed now is time like you said. I can't wait for what the future will bring. I will continue to monitor this repo and hopefully there will be a massive community for locally running these types of programs. Take your time, massive progress is being made.
> 
> Once again, massive thank you!

I'm glad to be a part of the AI revolution. There is so much more to come, this is just a nice flexible starting point for what it will become.  The potential is great.
