### ISSUE TITLE
Commands Being Sent To Prompt Include Full List Not Only Enabled

### ISSUE THREAD

**Issue by Electrofried** [Josh-XT/Agent-LLM#206]
### Description

When sending prompts through to the provider (tested with Ooga, none others) the full  list of commands is being sent through, not just those that are enabled.

### Steps to Reproduce the Bug

Start task with a subset of commands enabled.
Check prompt being sent to API.
See all commands on the list, not just the enabled ones.

### Expected Behavior

Only Enabled commands should be added to the prompt.

### Actual Behavior

All commands are added even disabled ones.

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Fixed in #207

**Comment by Josh-XT** [comment]
Found was still broken in execution agent and fixed there too im #220
