### ISSUE TITLE
(node:29) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by steppige** [Josh-XT/Agent-LLM#208]
### Description

When I launch the "docker-compose up" command everything seems to be fine, but as soon as I connect from the browser that error message comes out on the terminal. Also to connect I use port :3000 for the web interface, while here the error indicates port 80, I don't understand...

### Steps to Reproduce the Bug

1. docker-compose up
2. connect 127.0.0.1:3000
3. Error 

### Expected Behavior

When I launch the "docker-compose up" command everything seems to be fine, but as soon as I connect from the browser that error message comes out on the terminal. Also to connect I use port :3000 for the web interface, while here the error indicates port 80, I don't understand...

### Actual Behavior

This is error: 
`(vicuna-matata) steppi@ubuntu4090:~/sp2/Agent-LLM$ sudo docker-compose up
Starting agent-llm_backend_1 ... done
Starting agent-llm_frontend_1 ... done
Attaching to agent-llm_backend_1, agent-llm_frontend_1
frontend_1  | yarn run v1.22.19
frontend_1  | $ next start
frontend_1  | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
backend_1   | INFO:     Started server process [7]
backend_1   | INFO:     Waiting for application startup.
backend_1   | INFO:     Application startup complete.
backend_1   | INFO:     Uvicorn running on http://0.0.0.0:7437 (Press CTRL+C to quit)
backend_1   | INFO:     172.21.0.1:59966 - "GET /api/provider HTTP/1.1" 200 OK
frontend_1  | Promise { <pending> }
frontend_1  | {
frontend_1  |   mutate: [Function (anonymous)],
frontend_1  |   data: [Getter],
frontend_1  |   error: [Getter],
frontend_1  |   isValidating: [Getter],
frontend_1  |   isLoading: [Getter]
frontend_1  | }
frontend_1  | (node:29) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:80
frontend_1  |     at Function.AxiosError.from (file:///app/node_modules/axios/lib/core/AxiosError.js:89:14)
frontend_1  |     at RedirectableRequest.handleRequestError (file:///app/node_modules/axios/lib/adapters/http.js:591:25)
frontend_1  |     at RedirectableRequest.emit (events.js:400:28)
frontend_1  |     at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
frontend_1  |     at ClientRequest.emit (events.js:400:28)
frontend_1  |     at Socket.socketErrorListener (_http_client.js:475:9)
frontend_1  |     at Socket.emit (events.js:400:28)
frontend_1  |     at emitErrorNT (internal/streams/destroy.js:106:8)
frontend_1  |     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
frontend_1  |     at processTicksAndRejections (internal/process/task_queues.js:82:21)
frontend_1  | (Use `node --trace-warnings ...` to show where the warning was created)
frontend_1  | (node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
frontend_1  | (node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
frontend_1  | Promise { <pending> }
backend_1   | INFO:     172.21.0.1:59966 - "GET /api/provider HTTP/1.1" 200 OK
frontend_1  | (node:29) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:80
frontend_1  |     at Function.AxiosError.from (file:///app/node_modules/axios/lib/core/AxiosError.js:89:14)
frontend_1  |     at RedirectableRequest.handleRequestError (file:///app/node_modules/axios/lib/adapters/http.js:591:25)
frontend_1  |     at RedirectableRequest.emit (events.js:400:28)
frontend_1  |     at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
frontend_1  |     at ClientRequest.emit (events.js:400:28)
frontend_1  |     at Socket.socketErrorListener (_http_client.js:475:9)
frontend_1  |     at Socket.emit (events.js:400:28)
frontend_1  |     at emitErrorNT (internal/streams/destroy.js:106:8)
frontend_1  |     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
frontend_1  |     at processTicksAndRejections (internal/process/task_queues.js:82:21)
frontend_1  | (node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
backend_1   | INFO:     172.21.0.1:38128 - "GET /api/provider HTTP/1.1" 200 OK
`

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [X] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Setmaster** [comment]
I think it's similar to https://github.com/Josh-XT/Agent-LLM/issues/193#issuecomment-1533518780

**Comment by Josh-XT** [comment]
The port in Docker is 3000 if running inside of Docker, but port 80 is the exposed port when using docker.
