### ISSUE TITLE
HuggingChat keeps throwing up Invalid JSON Reponse error

### ISSUE THREAD

**Issue by timuryunuk2023** [Josh-XT/Agent-LLM#209]
### Description

Executing task 1: Develop a task list.

INFO:     127.0.0.1:50964 - "GET /api/agent/Test_AI/task/status HTTP/1.1" 200 OK
Invalid JSON response
Response: 

Task Result:

Response: Sure! Based on the given input, here is my suggested priority order for these tasks:

1. Priority 8 - Task 9: Create blog post about AI. (This task can provide more detailed information than a tweet)
2. Priority 2 - Task 3: Write a tweet about AI. (A tweet can quickly spread awareness about AI)
3. Priority 4 - Task 5: Clean up formatting on website pages. (Improving website appearance can make a good first impression)
4. Priority 6 - Task 7: Add new features to website. (New features can improve user experience and attract more visitors)
5. Priority 1 - Task 1: None (No specific task assigned to this priority level)
6. Priority 3 - Task 4: None (No specific task assigned to this priority level)
7. Priority 5 - Task 6: None (No specific task assigned to this priority level)
8. Priority 7 - Task 8: None (No specific task assigned to this priority level)

Please note that the above suggestions are based solely on the information provided and may change depending on other factors such as deadlines, available resources, etc.

Executing task 1: Priority 8 - Task 9: Create blog post about AI. (This task can provide more detailed information than a tweet)

Invalid JSON response
Response: 

Task Result:

Response: Sure! Based on the provided input, here are the tasks listed from highest priority (task #1) to lowest priority (task #13):

1. Create a project management tool to track progress on all active projects.
2. Prioritize high-priority projects and assign resources accordingly.
3. Develop a plan to address any bottlenecks or delays in project completion.
4. Identify areas where efficiency can be improved and implement changes.
5. Regularly review and update project timelines and milestones.
6. Provide regular updates to stakeholders on project status and progress.
7. Conduct risk assessments and develop contingency plans for potential issues.
8. Monitor resource utilization and adjust staffing levels as necessary.
9. Encourage communication and collaboration among team members.
10. Continuously evaluate and improve processes to increase overall productivity.
11. Create a knowledge base of common questions and answers related to our products and services.
12. Implement a customer feedback system to gather insights into their needs and preferences.
13. Automate repetitive administrative tasks using AI tools and software.
Please note that these priorities may change based on specific circumstances and context.

Executing task 1: Create a project management tool to track progress on all active projects.

Invalid JSON response
Response: 

Task Result:

Response: Here is your output: [('Priority 2', 'Task 3', {'description': 'Write a tweet about AI.'}), ('Priority 4', 'Task 5', {'description': 'Clean up formatting on website pages.'}), ('Priority 6', 'Task 7', {'description': 'Add new features to website.'})]

New Tasks:

[{'task_name': "Here is your output: [('Priority 2', 'Task 3', {'description': 'Write a tweet about AI.'}), ('Priority 4', 'Task 5', {'description': 'Clean up formatting on website pages.'}), ('Priority 6', 'Task 7', {'description': 'Add new features to website.'})]"}]

Response: Here is your output: [('Prioritize high-priority projects and assign resources accordingly', 'Develop a plan to address any bottlenecks or delays in project completion'), ('Identify areas where efficiency can be improved and implement changes', 'Create a knowledge base of common questions and answers related to our products and services')]

New Tasks:

[{'task_name': "Here is your output: [('Prioritize high-priority projects and assign resources accordingly', 'Develop a plan to address any bottlenecks or delays in project completion'), ('Identify areas where efficiency can be improved and implement changes', 'Create a knowledge base of common questions and answers related to our products and services')]"}]

Response: Sure! Here are some possible tasks related to researching about pizza that can be created based on the given input:

1. Search for popular pizza chains around the world.
2. Look into different types of crusts used in making pizzas.
3. Find out about the history of pizza and how it originated.
4. Investigate the nutritional value of different ingredients commonly used in pizza.
5. Explore regional variations in pizza recipes across different countries.
6. Learn about famous chefs who specialize in creating unique pizza dishes.
7. Discover new trends in the pizza industry such as gluten-free options or vegan alternatives.
8. Study the science behind baking perfect pizza at home.
9. Compare and contrast frozen vs freshly made pizza.
10. Create a list of must-try pizzerias in major cities around the globe.

Please note that these tasks may need further refinement depending on your specific needs and goals. Let me know if you have any questions or require additional assistance.

New Tasks:

[{'task_name': 'Sure! Here are some possible tasks related to researching about pizza that can be created based on the given input:'}, {'task_name': ''}, {'task_name': '1. Search for popular pizza chains around the world.'}, {'task_name': '2. Look into different types of crusts used in making pizzas.'}, {'task_name': '3. Find out about the history of pizza and how it originated.'}, {'task_name': '4. Investigate the nutritional value of different ingredients commonly used in pizza.'}, {'task_name': '5. Explore regional variations in pizza recipes across different countries.'}, {'task_name': '6. Learn about famous chefs who specialize in creating unique pizza dishes.'}, {'task_name': '7. Discover new trends in the pizza industry such as gluten-free options or vegan alternatives.'}, {'task_name': '8. Study the science behind baking perfect pizza at home.'}, {'task_name': '9. Compare and contrast frozen vs freshly made pizza.'}, {'task_name': '10. Create a list of must-try pizzerias in major cities around the globe.'}, {'task_name': ''}, {'task_name': 'Please note that these tasks may need further refinement depending on your specific needs and goals. Let me know if you have any questions or require additional assistance.'}]

Exception in thread Thread-7 (run_task):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/timur/Downloads/Agent-LLM-1.1.3-alpha/AgentLLM.py", line 341, in run_task
    self.prioritization_agent()
  File "/Users/timur/Downloads/Agent-LLM-1.1.3-alpha/AgentLLM.py", line 283, in prioritization_agent
    response = self.run(prompt, commands_enabled=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Downloads/Agent-LLM-1.1.3-alpha/AgentLLM.py", line 116, in run
    self.response = self.instruct(prompt)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timur/Downloads/Agent-LLM-1.1.3-alpha/provider/huggingchat.py", line 48, in instruct
    data = data[0] if data else {}
           ~~~~^^^
KeyError: 0
[2023-05-03 13:31:26,259] {duckdb.py:445} INFO - PersistentDuckDB del, about to run persist
[2023-05-03 13:31:26,259] {duckdb.py:388} INFO - Persisting DB to disk, putting it in the save folder: agents/Test_AI/memories
Response: 10. Priority 2 - Task 3: Write a tweet about AI. (A tweet can quickly spread awareness about AI)
9. Priority 4 - Task 5: Clean up formatting on website pages. (Improving website appearance can make a good first impression)
8. Priority 6 - Task 7: Add new features to website. (New features can improve user experience and attract more visitors)
7. Priority 1 - Task 1: None (No specific task assigned to this priority level)
6. Priority 3 - Task 4: None (No specific task assigned to this priority level)
5. Priority 5 - Task 6: None (No specific task assigned to this priority level)
4. Priority 7 - Task 8: None (No specific task assigned to this priority level)

Executing task 10: Priority 2 - Task 3: Write a tweet about AI. (A tweet can quickly spread awareness about AI)

Invalid JSON response
Response: 

Task Result:



Response: 15. Prioritize high-priority projects and assign resources accordingly.
16. Develop a plan to address any bottlenecks or delays in project completion.
17. Identify areas where efficiency can be improved and implement changes.
18. Regularly review and update project timelines and milestones.
19. Provide regular updates to stakeholders on project status and progress.
20. Conduct risk assessments and develop contingency plans for potential issues.
21. Monitor resource utilization and adjust staffing levels as necessary.
22. Encourage communication and collaboration among team members.
23. Continuously evaluate and improve processes to increase overall productivity.
24. Create a knowledge base of common questions and answers related to our products and services.
25. Implement a customer feedback system to gather insights into their needs and preferences.
26. Automate repetitive administrative tasks using AI tools and software.

Executing task 15: Prioritize high-priority projects and assign resources accordingly.

Invalid JSON response
Response: 

Task Result:
<img width="1420" alt="Знімок екрана 2023-05-03 о 13 33 40" src="https://user-images.githubusercontent.com/90114599/235917183-0edb2e6c-907c-4f13-98e6-489144a6d306.png">



### Steps to Reproduce the Bug

1. Start back and front ends
2. Go to agents page
3. Select agent.
4. Give it a task (mine is Research about pizza)


### Expected Behavior

Start to execute the task

### Actual Behavior

Throws Invalid JSON error

### Additional Context / Screenshots

_No response_

### Operating System

- [ ] Microsoft Windows
- [X] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [X] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Better error handling was added to help with this.
