### ISSUE TITLE
No agent startup

### ISSUE THREAD

**Issue by mtthw-meyer** [Josh-XT/Agent-LLM#22]
When you start it for the first time with no agents it returns a 500 with
FileNotFoundError: [Errno 2] No such file or directory: 'agents

Also you then have to manually refresh after adding an agent to get it to show up.

**Comment by Josh-XT** [comment]
You may need to create an "agents" folder. I guess GitHub didn't upload it because it is empty. You may also want to pull the latest.

**Comment by Josh-XT** [comment]
Should be good now, let me know if you're still having an issue.
