### ISSUE TITLE
No output or response in UI when starting a new Task-Agent

### ISSUE THREAD

**Issue by Copterz** [Josh-XT/Agent-LLM#222]
### Description

When I start a new task-agent task and click the 'Start Pursuing Task' button nothing happens in the UI. The button text does not change to 'Stop Pursuing Task' and the text box does not display the feedback from the task. I have checked that the feedback is indeed in the backend launch window, and the task is running.

### Steps to Reproduce the Bug

1. Goto Task-Agent
2. Enter a task
3. Click the 'Start Pursuing Task' button

### Expected Behavior

After clicking the Start Pursuing Task button, the button text should change to Stop Pursuing Task and the log / feedback of the running task should display in the text area below.

### Actual Behavior

The task appears to start but the UI is not updated to let the user know the current state of the running task.

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by lgwacker** [comment]
Same here, will try to debug that one.

**Comment by Josh-XT** [comment]
https://github.com/JamesonRGrieve/Agent-LLM-Frontend

Please direct front end issues to the front end repository.
