### ISSUE TITLE
Bard produces errors after running for a little while.

### ISSUE THREAD

**Issue by techgo** [Josh-XT/Agent-LLM#223]
### Description

I receive the below error when using Bard in continuous pursuit mode.
`backend_1   | Response: Google Bard encountered an error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[8]]]\n56\n[["di",100],["af.httprm",99,"-296488581439502604",15]]\n25\n[["e",4,null,null,131]]\n'.`

### Steps to Reproduce the Bug

Run Bard in continuous pursuit mode and eventually this error occurs.

### Expected Behavior

No error.

### Actual Behavior

This error:
`backend_1   | Response: Google Bard encountered an error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[8]]]\n56\n[["di",100],["af.httprm",99,"-296488581439502604",15]]\n25\n[["e",4,null,null,131]]\n'.`

### Additional Context / Screenshots

Log file: https://pastebin.com/DnnBb6vy

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [X] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
I haven't been able to dig extremely deep into this yet, but it is looking like Google may be enforcing rate limits potentially.

We use the GoogleBard python module from the link below, I think you may need to make this issue for them rather than Agent-LLM to see if anyone else is getting this.  I use Bard once in awhile for validation of results from smaller models in chains and haven't noticed this, but I am not drilling Bard, I am hitting it with a message every few minutes in my chain.

https://github.com/acheong08/Bard

**Comment by techgo** [comment]
> I haven't been able to dig extremely deep into this yet, but it is looking like Google may be enforcing rate limits potentially.
> 
> We use the GoogleBard python module from the link below, I think you may need to make this issue for them rather than Agent-LLM to see if anyone else is getting this. I use Bard once in awhile for validation of results from smaller models in chains and haven't noticed this, but I am not drilling Bard, I am hitting it with a message every few minutes in my chain.
> 
> https://github.com/acheong08/Bard

I appreciate your insight. No hard feelings if you think this ticket should be closed in light of it potentially being a Bard module issue.

**Comment by techgo** [comment]
Also, it does appear that I am not the only one with this issue. https://github.com/acheong08/Bard/issues/5

**Comment by Josh-XT** [comment]
> Also, it does appear that I am not the only one with this issue. Although, I am not sure if the cause is the same for them. [acheong08/Bard#5](https://github.com/acheong08/Bard/issues/5)

Yeah, just seems to be an issue with Bard limitations then.  The last comment says:

```
It looks like I ran out of Bard chat questions for my account, for the day (I hope for only 1 day at least)
```

I don't know that it is a daily limit, but I bet at least hourly.  I'm not sure if Google is clear about that anywhere.

**Comment by Josh-XT** [comment]
I'm also just guessing, but they may also expire session tokens after so many uses.

**Comment by rbayramo** [comment]
The rate limits for Bard vary depending on how you are using it. For example, if you are using Bard through the web interface, you can ask up to 200 questions per hour. If you are using Bard through the API, you will have a different set of limits. The specific limits for the API are not publicly available, but you can contact Google for more information.

Here are some general tips for avoiding rate limits when using Bard:

Don't ask too many questions in a short period of time.
Give Bard some time to respond before asking another question.
If you are using the API, be sure to use the correct parameters.
If you are still having trouble, you can contact Google for help.
Here are some additional details about the rate limits for the web interface:

You can ask up to 200 questions per hour.
You can ask up to 10 questions per minute.
There is a 10-second delay between questions.
If you exceed the rate limits, you will receive an error message. You will need to wait a few minutes before you can ask more questions.

**Comment by OlegRuban-ai** [comment]
When I use tokens on my computer, everything works. But if you run the same tokens (cookies) on another computer with the same version of GoogleBard, then the error "Google Bard encountered an error: b\')]}\\\'\\n\\n38\\n[[" is returned wrb.f...." Any solutions to the problem?

**Comment by greengeckowizard** [comment]
> When I use tokens on my computer, everything works. But if you run the same tokens (cookies) on another computer with the same version of GoogleBard, then the error "Google Bard encountered an error: b')]}\'\n\n38\n[[" is returned wrb.f...." Any solutions to the problem?

It's because you've reached the daily limit on your bard that's normal.
