### ISSUE TITLE
Can you create a usage manual for me? This program appears to be very powerful, but the user manual seems simple, not very practical to use, including instructions on using other suppliers' AI models and adding plugins.

### ISSUE THREAD

**Issue by Felixqian4160** [Josh-XT/Agent-LLM#232]
### Problem Description

Can you create a usage manual for me? This program appears to be very powerful, but the user manual seems simple, not very practical to use, including instructions on using other suppliers' AI models and adding plugins.

### Proposed Solution

Can you create a usage manual for me? This program appears to be very powerful, but the user manual seems simple, not very practical to use, including instructions on using other suppliers' AI models and adding plugins.

### Alternatives Considered

Can you create a usage manual for me? This program appears to be very powerful, but the user manual seems simple, not very practical to use, including instructions on using other suppliers' AI models and adding plugins.

### Additional Context

Can you create a usage manual for me? This program appears to be very powerful, but the user manual seems simple, not very practical to use, including instructions on using other suppliers' AI models and adding plugins.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by Josh-XT** [comment]
We plan to update our documentation soon. We just made a lot of updates in the past week but also are working our day jobs. This tool is extremely powerful, but yes, you have to know how to use it. If you have specific questions or issues, this is the place to ask or present those.

**Comment by Felixqian4160** [comment]
OK
