### ISSUE TITLE
Can access the webUI, and make a new agent, but can't have the agent do anything with openAI API key

### ISSUE THREAD

**Issue by RandomInternetPreson** [Josh-XT/Agent-LLM#233]
### Description

I've edited the .env file with my openAI API key and configured the agent via the webUI, I've tried the default gpt-3.5-turbo too, but nothing happens if I try to do any of the Chat, Instruct, or Task agent commands.

Any ideas :3

Also, I do have access to the gpt-4 api, I can successfully use it with Auto-GPT. 

### Steps to Reproduce the Bug

Install the latest alpha version or the main version and follow the docker install instructions.

### Expected Behavior

Expecting some type of response back, but get nothing after trying the chat, instruct, or task agent commands.

### Actual Behavior

I click on "start pursing task" for example and nothing happens.

### Additional Context / Screenshots

![image](https://user-images.githubusercontent.com/6488699/236642689-67e1bf3b-fd48-4d47-992a-3eb386a6f0ba.png)

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
https://github.com/JamesonRGrieve/Agent-LLM-Frontend

Please direct front end issues to the front end repository.
