### ISSUE TITLE
Sorry, I dont know why

### ISSUE THREAD

**Issue by LTMcqueen** [Josh-XT/Agent-LLM#235]
### Description

![image](https://user-images.githubusercontent.com/50995823/236661448-9c0e5b2b-f14c-4541-bfa5-5ddc7f6cf70c.png)
![image](https://user-images.githubusercontent.com/50995823/236661477-a8ea5541-4dc6-40f8-918b-30369740333b.png)
I can`t load the model and get access http://127.0.0.1:7437/

### Steps to Reproduce the Bug

python app.py

### Expected Behavior

load source successlly

### Actual Behavior

![image](https://user-images.githubusercontent.com/50995823/236661762-06cf007d-cd9e-4c75-9a92-8ebe21fff8ce.png)
![image](https://user-images.githubusercontent.com/50995823/236661778-bc1bb6d8-d10b-4260-b686-bf8b663c011f.png)

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Hello.  Apologies for our outdated documentation, but those environment variables for those settings are no longer necessary.  All provider settings are set per agent in the web interface now.  Please take a look at the latest readme.

https://github.com/Josh-XT/Agent-LLM
