### ISSUE TITLE
No such file or directory: 'prompts/execution.txt' (WSL2 env on Win11)

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/Agent-LLM#242]
### Description

I'm using `v1.1.6-alpha`

When i click the button "START PURSUING TASK", nothing happens in the UI

in the shell it says

```
Exception in thread Thread-2 (run_task):
Traceback (most recent call last):
  File "/home/mihai/miniconda3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/mihai/miniconda3/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mihai/Agent-LLM/AgentLLM.py", line 316, in run_task
    result = self.run(task=task["task_name"], prompt="execution")
  File "/home/mihai/Agent-LLM/AgentLLM.py", line 97, in run
    prompt = CustomPrompt().get_prompt(prompt)
  File "/home/mihai/Agent-LLM/CustomPrompt.py", line 17, in get_prompt
    with open(os.path.join("prompts", f"{prompt_name}.txt"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'prompts/execution.txt'
```

### Steps to Reproduce the Bug

1. add `OPENAI_API_BASE_URL=http://localhost:5001` to .env file
2. start app.py
3. start frontenv with npp run dev
4. open `http://[localhost:3000/agent](http://localhost:3000/agent)`
5. define new agent
6. configure agent with `Agent Provider = openai` and model `gpt-3.5-turbo`
7. navigate to tab `Control Agent [agent name]`
8. give the task of `write the text 'Hello Mihai!' into a txt file named 'testing.txt'`

### Expected Behavior

After clicking the button to appear a message that say the task is started or some other kind of information to now it started

### Actual Behavior

nothing happens in the UI.

only in terminal window can see it has errors

### Additional Context / Screenshots

I'm running text-generation-webui with the command

`python server.py --model TheBloke_GPT4All-13B-snoozy-GPTQ --disk --model_type Llama --listen --no-stream --auto-devices --verbose --xformers --sdp-attention --extensions api openai --bf16 --threads 4 --n_batch 128 --pre_layer 32 --gpu-memory 4 4 --chat --settings settings.json --cpu-memory 26 --wbits 4 --groupsize 128`

If i try the `CHAT WITH AGENT` tab and write the same text, the response given is:

```
  File "/home/mihai/.local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mihai/Agent-LLM/app.py", line 210, in chat
    response = agent.run(prompt.prompt, max_context_tokens=500, commands_enabled=False)
  File "/home/mihai/Agent-LLM/AgentLLM.py", line 113, in run
    self.response = self.CFG.instruct(formatted_prompt)
  File "/home/mihai/Agent-LLM/provider/openai.py", line 39, in instruct
    max_tokens=int(self.MAX_TOKENS - len(prompt)),
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

After i modify line 26 and 39  int the `/home/mihai/Agent-LLM/provider/openai.py`
from this
`max_tokens=int(self.MAX_TOKENS - len(prompt)),`
to this
`max_tokens=int(self.MAX_TOKENS) - len(prompt),`
then restart `app.py`, it works as exected, and the result is 
![Screenshot 2023-05-07 194320](https://user-images.githubusercontent.com/5344119/236690904-92bec169-df5b-4504-97d7-ece180e4c93e.png)

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Pull latest, the file name was wrong and has been fixed.
