### ISSUE TITLE
enabled_commands -> TypeError: object of type 'filter' has no len() 

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/Agent-LLM#246]
### Description

START PURSUING TASK

```
  File "/home/mihai/Agent-LLM/AgentLLM.py", line 75, in get_commands_string
    if len(enabled_commands) == 0:
TypeError: object of type 'filter' has no len()
```

### Steps to Reproduce the Bug

START PURSUING TASK

(agent provider = oobabooga)

### Expected Behavior

to run

### Actual Behavior

throws error

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by mongolu** [comment]
if i replace lines 72->76 in `AgentLLM.py` with `enabled_commands = self.available_commands`, restart `app.py`, other error is thrown:

```
  File "/home/mihai/Agent-LLM/AgentLLM.py", line 344, in run_task
    result = self.run(task=task["task_name"], prompt="execute")
  File "/home/mihai/Agent-LLM/AgentLLM.py", line 140, in run
    formatted_prompt, unformatted_prompt = self.format_prompt(
  File "/home/mihai/Agent-LLM/AgentLLM.py", line 121, in format_prompt
    formatted_prompt = prompt.format(
KeyError: '\n    "plan"'
```

**Comment by Mirddinhell** [comment]
It worked for me: I replaced line 75 from `if len(enabled_commands) == 0:` to `if len(list(enabled_commands)) == 0:`

**Comment by Josh-XT** [comment]
I just fixed this in the latest release, please pull the latest.
