### ISSUE TITLE
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "gunicorn": executable file not found in $PATH: unknown.

### ISSUE THREAD

**Issue by CRCODE22** [Josh-XT/Agent-LLM#25]
(llm-agent) D:\Agent-LLM>docker run -it --pull always -p 80:5000 --env-file=.env ghcr.io/josh-xt/agent-llm:main
main: Pulling from josh-xt/agent-llm
9fbefa337077: Pull complete
a25702e0699e: Pull complete
3ae62d6907d0: Pull complete
10b9ec96af43: Pull complete
b68090968714: Pull complete
1e4317f4f83e: Pull complete
c8440f2b2909: Pull complete
ffe57ad52e6e: Pull complete
b4aaa4755ffa: Pull complete
c18b659489b2: Pull complete
b20ec129a8b4: Pull complete
b385571020ba: Pull complete
0175eac0bcc3: Pull complete
341f1b3c2cec: Pull complete
Digest: sha256:c5847b4787451d826b5202e1354540362c109aa572b8cb958a82da44f1da63fb
Status: Downloaded newer image for ghcr.io/josh-xt/agent-llm:main
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "gunicorn": executable file not found in $PATH: unknown.

(llm-agent) D:\Agent-LLM>
![error5](https://user-images.githubusercontent.com/88407346/233749361-b6f13912-272d-48ee-b882-a21ab008d842.png)
![error4](https://user-images.githubusercontent.com/88407346/233749364-b1b14349-947d-4edb-874a-301737a1fc89.png)

**Comment by Josh-XT** [comment]
Just an update, I'm working on fixing docker stuff. It is now two packages since we've switched from react to NextJS.

**Comment by meezyart** [comment]
get this on the latest update

> docker compose up -d --build
[+] Building 0.1s (3/4)                                                                                                                   
 => [agent-llm-frontend internal] load build definition from Dockerfile                                                              0.0s
 => => transferring dockerfile: 495B                                                                                                 0.0s
 => [agent-llm-backend internal] load build definition from Dockerfile-backend                                                       0.0s
 => => transferring dockerfile: 2B                                                                                                   0.0s
 => [agent-llm-frontend internal] load .dockerignore                                                                                 0.0s
 => => transferring context: 2B                                                                                                      0.0s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3658666252/Dockerfile-backend: no such file or directory

**Comment by Josh-XT** [comment]
> get this on the latest update
> 
> > docker compose up -d --build
> > [+] Building 0.1s (3/4)
> > => [agent-llm-frontend internal] load build definition from Dockerfile                                                              0.0s
> > => => transferring dockerfile: 495B                                                                                                 0.0s
> > => [agent-llm-backend internal] load build definition from Dockerfile-backend                                                       0.0s
> > => => transferring dockerfile: 2B                                                                                                   0.0s
> > => [agent-llm-frontend internal] load .dockerignore                                                                                 0.0s
> > => => transferring context: 2B                                                                                                      0.0s
> > failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3658666252/Dockerfile-backend: no such file or directory

May have just fixed with the last push

**Comment by Josh-XT** [comment]
Replaced gunicorn with uvicorn and Flask with FastAPI tonight.  This should run with the docker-compose in the repo or the two docker run commands in the readme now.
