### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'str' and 'int' from oobabooga.py

### ISSUE THREAD

**Issue by dicksensei69** [Josh-XT/Agent-LLM#266]
### Description

When I have my provider set too oobabooga I try to run a task agent on any task it errors out on the tokens being both a str and int.  I could be doing something wrong but I haven't been able to get past the error. I have done a recent git pull and docker compose up -build. This is very similar behavior to what is listed in bug #251

Error message:
agent-llm-backend-1   | Executing task 1: Develop a task list.
agent-llm-backend-1   | 
agent-llm-backend-1   | INFO:     172.18.0.1:51576 - "GET /api/agent/brand_new/task/status HTTP/1.1" 200 OK
agent-llm-backend-1   | Exception in thread Thread-5 (run_task):
agent-llm-backend-1   | Traceback (most recent call last):
agent-llm-backend-1   |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
agent-llm-backend-1   |     self.run()
agent-llm-backend-1   |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
agent-llm-backend-1   |     self._target(*self._args, **self._kwargs)
agent-llm-backend-1   |   File "/app/AgentLLM.py", line 373, in run_task
agent-llm-backend-1   |     result = self.run(task=task["task_name"], prompt="execute")
agent-llm-backend-1   |   File "/app/AgentLLM.py", line 165, in run
agent-llm-backend-1   |     self.response = self.CFG.instruct(formatted_prompt, tokens=tokens)
agent-llm-backend-1   |   File "/app/provider/oobabooga.py", line 22, in instruct
agent-llm-backend-1   |     new_tokens = self.MAX_TOKENS - tokens
agent-llm-backend-1   | TypeError: unsupported operand type(s) for -: 'str' and 'int'

### Steps to Reproduce the Bug

1. git pull
2. docker compose up -build
3. navigate to localhost:3000 in web browser
4. make a new user
5. set provider to oobabooga 
6. set uri, context length, temp, model (any vicuna, default)
7. enter task for agent "write me a short story"
8. click start pursuing task
9. nothing happens 

### Expected Behavior

To start trying to complete the task the agent is given with the local install of oogabooga text generation.

### Actual Behavior

If you start docker without -d you can see the backend fail with the above error.

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by mongolu** [comment]
You could try modifying that line
`new_tokens = self.MAX_TOKENS - tokens`
like so
`new_tokens = int(self.MAX_TOKENS) - tokens`

For me it resolved the problem.

**Comment by mongolu** [comment]
But I see in `v1.1.14-beta` it was modified, so try this version.

**Comment by Electrofried** [comment]
This is an issue in the agent config, not for the provider.

If you go in to the agent config manually, (data folder, agent name, config) and edit the end of the line to change "2048" (or whatever you have it set to) to 2048 without the "" it will resolve the issue for now. I have not looked where the agent config is getting saved  in code yet but it will need to be fixed in there to resolve this.

**Comment by dicksensei69** [comment]
Thanks a bunch, now I'm back to my original error with connecting to the api of textgen.  Probably another issue with the new json format? I dunno when I enter the normal url http://127.0.0.1:5000 it hits nothing.  I have tested to see if something else is wrong with textgen's api but it seems good.  There are some formatting errors it pushes out if I do anything other than http://127.0.0.1:5000 eg. it will add extra api like http://127.0.0.1:5000/api/api/v1/generate if you use http://127.0.0.1:5000/api or if you leave the slash at the back end it shows http://127.0.0.1:5000//api/v1/generate. Anyway back to the error I was experiencing before the str-int confilct.  That was definitely the fix Electorfried. Here is a sample of the next error.  I'll give it a bit and make a new bug report if it persists but I understand this is a very active project. 


agent-llm-backend-1   | During handling of the above exception, another exception occurred:
agent-llm-backend-1   | 
agent-llm-backend-1   | Traceback (most recent call last):
agent-llm-backend-1   |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
agent-llm-backend-1   |     self.run()
agent-llm-backend-1   |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
agent-llm-backend-1   |     self._target(*self._args, **self._kwargs)
agent-llm-backend-1   |   File "/app/AgentLLM.py", line 373, in run_task
agent-llm-backend-1   |     result = self.run(task=task["task_name"], prompt="execute")
agent-llm-backend-1   |   File "/app/AgentLLM.py", line 165, in run
agent-llm-backend-1   |     self.response = self.CFG.instruct(formatted_prompt, tokens=tokens)
agent-llm-backend-1   |   File "/app/provider/oobabooga.py", line 45, in instruct
agent-llm-backend-1   |     response = requests.post(f"{self.AI_PROVIDER_URI}/api/v1/generate", json=params)
agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
agent-llm-backend-1   |     return request("post", url, data=data, json=json, **kwargs)
agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
agent-llm-backend-1   |     return session.request(method=method, url=url, **kwargs)
agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
agent-llm-backend-1   |     resp = self.send(prep, **send_kwargs)
agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
agent-llm-backend-1   |     r = adapter.send(request, **kwargs)
agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
agent-llm-backend-1   |     raise ConnectionError(e, request=request)
agent-llm-backend-1   | requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v1/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4c14bf160>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by Josh-XT** [comment]
Should be fixed in #273
