### ISSUE TITLE
Problem with .env.example?

### ISSUE THREAD

**Issue by R4X70N** [Josh-XT/Agent-LLM#282]
### Description

In the recent commit, the first 58 lines of the .env.example file were deleted.

### Steps to Reproduce the Bug

1. Go to the repository
2. Open the .env.example file
3. Check out commit cf555f8
4. Notice the first 58 lines are missing

### Expected Behavior

The .env.example file should retain all lines, including the crucial environment setup details contained in lines 1-58.

### Actual Behavior

When checking the .env.example file in the specified commit, lines 1-58 are absent, leaving the file incomplete.

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [ ] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Those lines were removed intentionally.  All of those settings have been moved to per agent settings and out of the `.env`.
