### ISSUE TITLE
Suggestion: Add config option to provider/oobabooga.py to allow setting ip for oobabooga host. 

### ISSUE THREAD

**Issue by Electrofried** [Josh-XT/Agent-LLM#3]
Users may not be hosting oobabooga on their local machine. It would be nice to have a config option (that defaults to localhost) so that we can point it at a specific IP in the case that oobabooga is being hosted elsewhere. 
Is this possible?

Thanks for all the work you are doing, this project is looking fantastic!

**Comment by Josh-XT** [comment]
Added a new environment variable called `AI_PROVIDER_URI` and have it set default to http://127.0.0.1:7860 for Oobabooga since it will only be referenced by it currently.  You can modify it in your `.env` file to customize it now.

**Comment by Electrofried** [comment]
Can confirm this is working now! Thanks!
