### ISSUE TITLE
Playwright Sync API inside the asyncio loop error

### ISSUE THREAD

**Issue by Qualzz** [Josh-XT/Agent-LLM#310]
### Description

Using playwright doesn't work for me: 

```
COMMANDS:
{'scrape_text': {'url': 'REDACTED'}}

Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
```

Did I missed something in the installation process or some configuration ? 
I'm sorry if this is a wrong report, this can be totally my fault. 

### Steps to Reproduce the Bug

1. Start an instruction using any of the playwright command. 

### Expected Behavior

Task complete

### Actual Behavior

Error: It looks like you are using Playwright Sync API inside the asyncio loop.

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Make sure your playwright version is up to date.
