### ISSUE TITLE
Issues with connecting to Oogabooga through API (soft solution inside)

### ISSUE THREAD

**Issue by dicksensei69** [Josh-XT/Agent-LLM#319]
### Description

I wasn't able to get AgentLLM to connect to my oogabooga textgen and I thought I needed to share how I got that working because it is not that straight forward.  You will error if you use http://0.0.0.0:5000 and you are on linux.  Same goes for 127.0.0.1 and everything else I tried.  Here is what the error will look like for you if you try to get things done the wrong way like I did.

agent-llm-backend-1   | During handling of the above exception, another exception occurred:
agent-llm-backend-1   | 
agent-llm-backend-1   | Traceback (most recent call last):
agent-llm-backend-1   |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
agent-llm-backend-1   |     self.run()
agent-llm-backend-1   |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
agent-llm-backend-1   |     self._target(*self._args, **self._kwargs)
agent-llm-backend-1   |   File "/app/AgentLLM.py", line 379, in run_task
agent-llm-backend-1   |     result = self.run(task=task["task_name"], prompt="execute")
agent-llm-backend-1   |   File "/app/AgentLLM.py", line 135, in run
agent-llm-backend-1   |     self.response = self.CFG.instruct(formatted_prompt, tokens=tokens)
agent-llm-backend-1   |   File "/app/provider/oobabooga.py", line 45, in instruct
agent-llm-backend-1   |     response = requests.post(f"{self.AI_PROVIDER_URI}/api/v1/generate", json=params)
agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
agent-llm-backend-1   |     return request("post", url, data=data, json=json, **kwargs)
agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
agent-llm-backend-1   |     return session.request(method=method, url=url, **kwargs)
agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
agent-llm-backend-1   |     resp = self.send(prep, **send_kwargs)
agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
agent-llm-backend-1   |     r = adapter.send(request, **kwargs)
agent-llm-backend-1   |   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
agent-llm-backend-1   |     raise ConnectionError(e, request=request)
agent-llm-backend-1   | requests.exceptions.ConnectionError: HTTPConnectionPool(host='host.docker.internal', port=5000): Max retries exceeded with url: /api/v1/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbd12a29d80>: Failed to establish a new connection: [Errno -2] Name or service not known'))

This error is the same error I got for the http://0.0.0.0:5000 and http://localhost:5000 and here with the http://host.docker.internal:5000
I eventually got it to work by talking about it with bing for a bit which brings me how to fix the issue.

Here is bings take
_From the error message you provided, it looks like the container is trying to connect to the API using the host.docker.internal DNS name, but it is unable to resolve it to an IP address. This can happen if you are using an older version of Docker or if you are running Docker on a non-desktop platform such as Linux.

If you are running Docker on Linux, the host.docker.internal DNS name is not supported by default. In this case, you can try using the IP address of the docker0 network interface on the host machine instead. You can find this IP address by running the command ip addr show docker0 on the host machine and looking for the inet line. The IP address should be in the format x.x.x.x/16. Use this IP address instead of host.docker.internal in your API endpoint URL.

If you are using an older version of Docker, you may need to update to a newer version that supports the host.docker.internal DNS name.

Let me know if this helps or if you have any further questions._

So when I ran ip addr show docker0 I found that the inet was 
inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0

I then used this as my uri
http://172.17.0.1:5000

and now my 30b model in oogabooga is writing it's sorry.  Hope this helps someone out there.

### Steps to Reproduce the Bug

1. git pull
2. docker compose up --build
3. use the webui to make an agent with all details and a uri of the oogabooga textgen of http://0.0.0.0:5000 or http://127.0.0.1:5000
4. it fails as it hits max attempts on an unreachable api

### Expected Behavior

It connects to the api and correctly generates text.

### Actual Behavior

Fails to connect because connecting to the docker container is different than a normal connection I guess

### Additional Context / Screenshots

This looks like it might be a problem for people not on windows and using a normal docker install (it may not show up if you are using docker desktop I'd guess but the way I installed docker seems to make this happen.

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
If you're running ooba in **docker**, `it isn't at your localhost.`

Docker acts as if it is another computer, anything you run in docker has its own IP, its own firewall rules, etc. This is the reason we do not define this to go to `http://localhost:5000` directly, we suggest it in the docs for if you're running it locally, but you have to put the IP address or hostname of where it resides, it will not work at "localhost" in docker unless you set your docker to do that.
