### ISSUE TITLE
Provider: Oobabooga Not Working Correctly

### ISSUE THREAD

**Issue by Electrofried** [Josh-XT/Agent-LLM#32]
Apparently the agents are set up in a way that they only expect to receive the response back from the API, however text-gen-ui using the gradio api currently sends back the entire prompt along with new text generated and I believe it is causing issues in actually getting the agents to function. Mostly because the task list becomes the entire prompt and returned list and things go a bit haywire from there.

Also might need to look in to what returned characters are stripped from the text as there are a lot of // in the /// text/ showing up/ like this/ .

One solution may be to move to using the actual api extension for the app.

You can find it here: https://github.com/oobabooga/text-generation-webui/blob/main/extensions/api/script.py

Though it would also require having users launch with the correct arguments.

*Edit*
I will do some further testing with the api extension tomorrow however it should be possible to use the existing kobold provider with it as it supports the same functions.

**Comment by Josh-XT** [comment]
I made some modifications earlier to help remove some of the slashes in the output.  Let me know how it is looking when you have some time.

**Comment by dany-on-demand** [comment]
FWIW I think this was fixed
