### ISSUE TITLE
XMLHttpRequest has been blocked by CORS policy

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/Agent-LLM#324]
### Description

When I click the button `ADD A NEW AGENT` the error appears in the backend terminal
```
File "/app/Memories.py", line 20, in init
if self.CFG.AI_PROVIDER == "openai":
AttributeError: 'Agent' object has no attribute 'AI_PROVIDER'
```
and in the browser console the error
```
Also in browser console it throws the error:
Access to XMLHttpRequest at 'http://localhost:7437/api/agent' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

this error appears in `v1.1.29-beta` but not in `v1.1.28-beta`

### Steps to Reproduce the Bug

1. Go to page `http://localhost:3000/new/agent`
2. Put agent name "xxx" or smth
3. Press `ADD A NEW AGENT`
4. Error in frontend
```
Unhandled Runtime Error
AxiosError: Network Error

Call Stack
XMLHttpRequest.handleError
node_modules/axios/lib/adapters/xhr.js (158:0)
```
6. Observe the error in backend terminal
```
  File "/home/mihai/.local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mihai/Agent-LLM/app.py", line 130, in add_agent
    agent_info = Agent(agent.agent_name).add_agent(agent.agent_name, agent.settings)
  File "/home/mihai/Agent-LLM/Config/Agent.py", line 40, in __init__
    if self.AI_PROVIDER == "openai":
AttributeError: 'Agent' object has no attribute 'AI_PROVIDER'
```
7. ls -ls agents shows a directory with the name introduced at step 2

### Expected Behavior

To create new agent w/o error

### Actual Behavior

The page throws that error, the backend says `AttributeError: 'Agent' object has no attribute 'AI_PROVIDER'`, in the web page the new agent doesn't appear

### Additional Context / Screenshots

browser Chrome Version 113.0.5672.93 (Official Build) (64-bit)

Win11 on WSL2

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by localagi** [comment]
Do you run on dockerized or bare metal (shell)?

**Comment by localagi** [comment]
@Josh-XT maybe it's related to an unexpected path in this if-else-tree

https://github.com/Josh-XT/Agent-LLM/blob/b66c02cd12ceffc9839068b5a7112dc99256b7fb/Config/Agent.py#L24

I'd be happy to clean it up as soon as I know what config cases it tries to catch

**Comment by Josh-XT** [comment]
> 

I may have just fixed it in the last commit.  There were not default provider settings being set upon agent creation if it wasn't created with settings.  Now it defaults to huggingchat.

**Comment by Josh-XT** [comment]
https://github.com/Josh-XT/Agent-LLM/commit/abefe132f5e53569faa80b6071b9771ced3edd74
See last commit and let us know if still having issues.
