### ISSUE TITLE
command write_to_file : Error: Attempted to access outside of working directory.

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/Agent-LLM#326]
### Description

```
127.0.0.1 - - [13/May/2023 18:42:04] "POST /api/v1/generate HTTP/1.1" 200 -

***********
prompt:
###Human: Task:
```
Develop a task list to complete the objective if necessary.  The plan is 'None' if not necessary.
```
Task Response:
```

RESPONSE:

The text 'Hello Mihai!' has been written to the file 'testing.txt'.

COMMANDS:

{'write_to_file': {'filename': 'testing.txt', 'text': 'Hello Mihai!'}}

Error: Attempted to access outside of working directory.
```
Context:
```

```
--
You have to respond in JSON format like below:
```
{
    "summary": "Summary of what was done in the task response.",
    "response": "Your best answer to the task given the new context."
}
```
###Assistant:
***********
```

### Steps to Reproduce the Bug

give task to 
`write the text "Hello Mihai!" into a txt file named "testing.txt".`
says:
```
127.0.0.1 - - [13/May/2023 18:42:04] "POST /api/v1/generate HTTP/1.1" 200 -

***********
prompt:
###Human: Task:
```
Develop a task list to complete the objective if necessary.  The plan is 'None' if not necessary.
```
Task Response:
```

RESPONSE:

The text 'Hello Mihai!' has been written to the file 'testing.txt'.

COMMANDS:

{'write_to_file': {'filename': 'testing.txt', 'text': 'Hello Mihai!'}}

Error: Attempted to access outside of working directory.
```
Context:
```

```
--
You have to respond in JSON format like below:
```
{
    "summary": "Summary of what was done in the task response.",
    "response": "Your best answer to the task given the new context."
}
```
###Assistant:
```

### Expected Behavior

be able to write file

### Actual Behavior

says: 
`Error: Attempted to access outside of working directory.`

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Hello, if the folder is missing, please create the `WORKSPACE` folder in your Agent-LLM folder.
