### ISSUE TITLE
Cover usecase of privateGPT (parse and ask about local, private documents)

### ISSUE THREAD

**Issue by localagi** [Josh-XT/Agent-LLM#328]
### Problem Description

parse documents locally...just stumbled accross this project. If interesting will more dig into deep and fill out this FR. If not, leaving this here for wontfix reference :)

https://github.com/imartinez/privateGPT

### Proposed Solution

see above

### Additional Context

https://github.com/imartinez/privateGPT

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by Josh-XT** [comment]
We already support both providers that they're running local models with and we can also run entirely local with both of those providers.
