### ISSUE TITLE
Command: Add SearXNG as Search Provider

### ISSUE THREAD

**Issue by Electrofried** [Josh-XT/Agent-LLM#33]
Api info here: https://docs.searxng.org/dev/search_api.html

Google API is limited, needs a key, you only get 100 queries and then have to pay. 
Other options exist but face many of the same issues.
SearXNG can be implemented via docker and loaded locally to provide meta search and results returned in json if you enable it in the docker configs. 

you can see an example implementation from langchain here:
https://python.langchain.com/en/latest/_modules/langchain/utilities/searx_search.html?highlight=searxng#

**Comment by Josh-XT** [comment]
Thanks for the good info!  Sounds like a good idea for a new command.  I haven't personally used SearXNG, but I can plan to implement this in the future after I get through some of the bugs.

**Comment by Josh-XT** [comment]
#97 Merged to begin SearXNG support.  Please create a new issue if there are any issues.
