### ISSUE TITLE
RuntimeWarning

### ISSUE THREAD

**Issue by lightningRalf** [Josh-XT/Agent-LLM#359]
### Description

When I start `streamlit run streamlit.py`

I get this: .../pydub/utils.py: 170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
warn( "Couldn't find ffmpeg or toffmpeg,but may not work" , Runtimewarning)

### Steps to Reproduce the Bug

1. pull from git
2. `streamlit run streamlit.py`
3. start up the streamlit app in browser
4. get error

### Expected Behavior

no warning

### Actual Behavior

got warning.

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
That is coming from one of the providers that requires it but apparently did not put it in their requirements.  

This should help:

```
pip install ffmpeg
```

**Comment by Josh-XT** [comment]
Added ffmpeg to requirements.
