### ISSUE TITLE
NEtwork Error

### ISSUE THREAD

**Issue by alexl83** [Josh-XT/Agent-LLM#37]
Hi, followed quickstart - docker-compose built succesfully
when connecting to Agent-LLM (running on workstation) from my laptop (same subnet)
I get a network error - uploading screenshot

Can you point me to the right sirection pleasE?
I'm doing something wrong probably

Thank you!
![Screenshot 2023-04-22 alle 23 37 09](https://user-images.githubusercontent.com/18349597/233807708-74b620ce-5df2-437c-899c-ca274ead7b40.jpg)

**Comment by samirma** [comment]
Same issue here :(

**Comment by Josh-XT** [comment]
Hello! This issue came up right after we pushed our new front end due to NextJS server behavior. I've replaced Flask with FastAPI today which solves the issue at the same time. If you can pull the latest, that should be fixed.

**Comment by alexl83** [comment]
I'm sorry, being on commit e13566bec088269298ad866cc976169fb6561c3c still same issue

I have backend and frontend built using
`docker-compose up -d --build`
running both on 192.168.1.128

I'm accessing the fronted from my laptop at 192.138.1.132

I also added `NEXT_PUBLIC_API_URI=https://moppio.local:80` in frontend/.env.local

behavior is the same - network error

**Comment by mkaushish** [comment]
Facing the same issue on the latest commit
<img width="231" alt="Screenshot 2023-04-24 at 9 21 58 AM" src="https://user-images.githubusercontent.com/1131632/233896283-428d1408-5a1d-46b7-97d6-f95df10e464f.png">

**Comment by samirma** [comment]
The issue persists. When I was trying to run locally, I noticed that when I opened the frontend, it didn't trigger the backend. So I tried something silly that worked. I replaced all instances of 'localhost' with '127.0.0.1' in the frontend, and it worked. The interface still doesn't show the agent status properly, but at least I can navigate and send actions to it.

I am not sure if it is related, but I am using mac

**Comment by alexl83** [comment]
Still persists; only way to have backend+frontend on a machine and accessing them from another, is to include a frontend/.env.local withvariable NEXT_PUBLIC_API_URI=<http://backend:5000>

I tried including the variable in docker-compose.yml alone, but it's not working, I'm not a fan of hardconding variables in programs and don't really know how to include the frontend/.env.local in docker container

Also, it would be nice to have a shared dir with container to make llama model accessible from docker instance
It would also be useful to switch from pyllama to llama-cpp-python for a performance boost
Additional prompts for other llama fine tunes would be great (koala, open-assistant, etc)

Hope this features will come to the agent with this fast developments happening :)
Unfgortunately I don't think tickets can be reopened and I don't feel raising additional ones over the same issues, don't really want to seem rude to developers, they're investing their free time in this outstanding projects

Fingers crossed; hopefully this suggestions can be considered with time :)
