### ISSUE TITLE
Arm64  cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/Agent-LLM#372]
### Description

When you try to use tasks or chat,instruct this error will occur where it fails to start the agents.

### Steps to Reproduce the Bug

1.Start Docker Container Streamlit
2.Access the webui on Streamlit
3.Create Agent (Bard,Palm,gpt4free)
4.Go to tasks
5.Create a task and start it
6.Watch logs Error will show on the logs on streamlit backend

### Expected Behavior

I expect the tasks,chat,instruct to function and run properly.

### Actual Behavior

agent-llm-backend-streamlit-1  | 2023-05-18 00:23:35.743 Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
agent-llm-backend-streamlit-1  | 2023-05-18 00:23:35.744 Running Chroma using direct local API.
agent-llm-backend-streamlit-1  | 2023-05-18 00:23:35.745 Using embedded DuckDB with persistence: data will be stored in: agents/bees/memories
agent-llm-backend-streamlit-1  | 2023-05-18 00:23:35.751 Uncaught app exception
agent-llm-backend-streamlit-1  | Traceback (most recent call last):
agent-llm-backend-streamlit-1  |   File "/app/Memories.py", line 32, in initialize_chroma_client
agent-llm-backend-streamlit-1  |     return chromadb.Client(
agent-llm-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/__init__.py", line 94, in Client
agent-llm-backend-streamlit-1  |     return chromadb.api.local.LocalAPI(settings, get_db(settings), telemetry_client)
agent-llm-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/__init__.py", line 49, in get_db
agent-llm-backend-streamlit-1  |     import chromadb.db.duckdb
agent-llm-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/db/duckdb.py", line 3, in <module>
agent-llm-backend-streamlit-1  |     from chromadb.db.clickhouse import (
agent-llm-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/db/clickhouse.py", line 11, in <module>
agent-llm-backend-streamlit-1  |     from chromadb.db.index.hnswlib import Hnswlib, delete_all_indexes
agent-llm-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/db/index/hnswlib.py", line 7, in <module>
agent-llm-backend-streamlit-1  |     import hnswlib
agent-llm-backend-streamlit-1  | ImportError: /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block
agent-llm-backend-streamlit-1  |
agent-llm-backend-streamlit-1  | During handling of the above exception, another exception occurred:
agent-llm-backend-streamlit-1  |
agent-llm-backend-streamlit-1  | Traceback (most recent call last):
agent-llm-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
agent-llm-backend-streamlit-1  |     exec(code, module.__dict__)
agent-llm-backend-streamlit-1  |   File "/app/streamlit.py", line 337, in <module>
agent-llm-backend-streamlit-1  |     agent = AgentLLM(agent_name)
agent-llm-backend-streamlit-1  |   File "/app/AgentLLM.py", line 37, in __init__
agent-llm-backend-streamlit-1  |     self.memories = Memories(self.agent_name, self.CFG)
agent-llm-backend-streamlit-1  |   File "/app/Memories.py", line 20, in __init__
agent-llm-backend-streamlit-1  |     self.chroma_client = self.initialize_chroma_client()
agent-llm-backend-streamlit-1  |   File "/app/Memories.py", line 39, in initialize_chroma_client
agent-llm-backend-streamlit-1  |     raise RuntimeError(f"Unable to initialize chroma client: {e}")
agent-llm-backend-streamlit-1  | RuntimeError: Unable to initialize chroma client: /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block
agent-llm-frontend-1           | Promise { <pending> }
agent-llm-frontend-1           | (node:29) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:7437
agent-llm-frontend-1           |     at Function.AxiosError.from (file:///app/node_modules/axios/lib/core/AxiosError.js:89:14)
agent-llm-frontend-1           |     at RedirectableRequest.handleRequestError (file:///app/node_modules/axios/lib/adapters/http.js:591:25)
agent-llm-frontend-1           |     at RedirectableRequest.emit (events.js:400:28)
agent-llm-frontend-1           |     at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
agent-llm-frontend-1           |     at ClientRequest.emit (events.js:400:28)
agent-llm-frontend-1           |     at Socket.socketErrorListener (_http_client.js:475:9)
agent-llm-frontend-1           |     at Socket.emit (events.js:400:28)
agent-llm-frontend-1           |     at emitErrorNT (internal/streams/destroy.js:106:8)
agent-llm-frontend-1           |     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
agent-llm-frontend-1           |     at processTicksAndRejections (internal/process/task_queues.js:82:21)
agent-llm-frontend-1           | (Use `node --trace-warnings ...` to show where the warning was created)
agent-llm-frontend-1           | (node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
agent-llm-frontend-1           | (node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
agent-llm-backend-streamlit-1  | 2023-05-18 00:23:35.743 Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
agent-llm-backend-streamlit-1  | 2023-05-18 00:23:35.744 Running Chroma using direct local API.
agent-llm-backend-streamlit-1  | 2023-05-18 00:23:35.745 Using embedded DuckDB with persistence: data will be stored in: agents/bees/memories
agent-llm-backend-streamlit-1  | 2023-05-18 00:23:35.751 Uncaught app exception
agent-llm-backend-streamlit-1  | Traceback (most recent call last):
agent-llm-backend-streamlit-1  |   File "/app/Memories.py", line 32, in initialize_chroma_client
agent-llm-backend-streamlit-1  |     return chromadb.Client(
agent-llm-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/__init__.py", line 94, in Client
agent-llm-backend-streamlit-1  |     return chromadb.api.local.LocalAPI(settings, get_db(settings), telemetry_client)
agent-llm-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/__init__.py", line 49, in get_db
agent-llm-backend-streamlit-1  |     import chromadb.db.duckdb
agent-llm-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/db/duckdb.py", line 3, in <module>
agent-llm-backend-streamlit-1  |     from chromadb.db.clickhouse import (
agent-llm-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/db/clickhouse.py", line 11, in <module>
agent-llm-backend-streamlit-1  |     from chromadb.db.index.hnswlib import Hnswlib, delete_all_indexes
agent-llm-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/chromadb/db/index/hnswlib.py", line 7, in <module>
agent-llm-backend-streamlit-1  |     import hnswlib
agent-llm-backend-streamlit-1  | ImportError: /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block
agent-llm-backend-streamlit-1  |
agent-llm-backend-streamlit-1  | During handling of the above exception, another exception occurred:
agent-llm-backend-streamlit-1  |
agent-llm-backend-streamlit-1  | Traceback (most recent call last):
agent-llm-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
agent-llm-backend-streamlit-1  |     exec(code, module.__dict__)
agent-llm-backend-streamlit-1  |   File "/app/streamlit.py", line 337, in <module>
agent-llm-backend-streamlit-1  |     agent = AgentLLM(agent_name)
agent-llm-backend-streamlit-1  |   File "/app/AgentLLM.py", line 37, in __init__
agent-llm-backend-streamlit-1  |     self.memories = Memories(self.agent_name, self.CFG)
agent-llm-backend-streamlit-1  |   File "/app/Memories.py", line 20, in __init__
agent-llm-backend-streamlit-1  |     self.chroma_client = self.initialize_chroma_client()
agent-llm-backend-streamlit-1  |   File "/app/Memories.py", line 39, in initialize_chroma_client
agent-llm-backend-streamlit-1  |     raise RuntimeError(f"Unable to initialize chroma client: {e}")
agent-llm-backend-streamlit-1  | RuntimeError: Unable to initialize chroma client: /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block
agent-llm-frontend-1           | Promise { <pending> }
agent-llm-frontend-1           | (node:29) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:7437
agent-llm-frontend-1           |     at Function.AxiosError.from (file:///app/node_modules/axios/lib/core/AxiosError.js:89:14)
agent-llm-frontend-1           |     at RedirectableRequest.handleRequestError (file:///app/node_modules/axios/lib/adapters/http.js:591:25)
agent-llm-frontend-1           |     at RedirectableRequest.emit (events.js:400:28)
agent-llm-frontend-1           |     at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
agent-llm-frontend-1           |     at ClientRequest.emit (events.js:400:28)
agent-llm-frontend-1           |     at Socket.socketErrorListener (_http_client.js:475:9)
agent-llm-frontend-1           |     at Socket.emit (events.js:400:28)
agent-llm-frontend-1
****

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [ ] Local
- [X] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Checked around online a little bit, looks like you may need to add this to your .bashrc file:
```
export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1:$LD_PRELOAD
```

Ref: https://stackoverflow.com/questions/61065541/importerror-usr-lib-aarch64-linux-gnu-libgomp-so-1-cannot-allocate-memory-in

**Comment by greengeckowizard** [comment]
> Checked around online a little bit, looks like you may need to add this to your .bashrc file:
> 
> ```
> export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1:$LD_PRELOAD
> ```
> 
> Ref: https://stackoverflow.com/questions/61065541/importerror-usr-lib-aarch64-linux-gnu-libgomp-so-1-cannot-allocate-memory-in

Already tried this and didn't fix it. Last fix I tried before the new docker hub implementation was just updating dependencies and that seemed to fix it. Now it's not working after this change with docker.but 6

**Comment by greengeckowizard** [comment]
Fixed
