### ISSUE TITLE
How do I interact with the program?

### ISSUE THREAD

**Issue by DRGSiler** [Josh-XT/Agent-LLM#40]
I've put all my information in the .env file and I have the basic program running on the 5000 local host channel but I have no idea how to interact with the ai or where to type requests.

**Comment by Josh-XT** [comment]
Hello!  Please refer to our quick start guide.  Port 5000 is the back end API server, the front end should be up at port 80 if running with docker-compose.

https://github.com/Josh-XT/Agent-LLM#quick-start
