### ISSUE TITLE
Add support for remote use

### ISSUE THREAD

**Issue by Senior-S** [Josh-XT/Agent-LLM#43]
If you set up the Agent LLM on a remote machine and join the website, it will try to connect to localhost instead the remote IP.

![image](https://user-images.githubusercontent.com/57560155/233821367-9726eb1c-67ef-4035-96ee-654460b9e8e4.png)

Edit: I didn't find any support for edit the IPs of the website nor the API. I find out that running `next start -p {port}` can change the port of the website but don't find how to change the API one.

**Comment by eraviart** [comment]
Create a file `frontend/.env.local` with something like:
```
NEXT_PUBLIC_API_URI=https://YOUR.DOMAIN:PORT
```

Then run `npm run build` in `frontend` directory.

**Comment by alexl83** [comment]
Don't know if it's related, but I keep getting "network error" from the frontend
both frontend and backend are running on 192.138.1.138
client is connecting from 192.168.1.132

![Screenshot 2023-04-23 alle 16 11 10](https://user-images.githubusercontent.com/18349597/233844764-0732be2f-1611-497a-acb7-f91892898c6e.jpg)

**Comment by Josh-XT** [comment]
> Don't know if it's related, but I keep getting "network error" from the frontend both frontend and backend are running on 192.138.1.138 client is connecting from 192.168.1.132
> 
> ![Screenshot 2023-04-23 alle 16 11 10](https://user-images.githubusercontent.com/18349597/233844764-0732be2f-1611-497a-acb7-f91892898c6e.jpg)

That issue should be have been fixed by the updates that went out this morning. You may need to pull latest changes.

**Comment by alexl83** [comment]
I'm on git abd538e30729cea3bf30d1b66811842c657c3243 and docker-compose pulls tag 1.0.2
I'm no expert, definitely doing something wrong

**Comment by Josh-XT** [comment]
> 

You'll want to update to 1.0.3.  I've been doing lots of updating, testing, and bug fixing this morning.  More to come.

**Comment by alexl83** [comment]
Pulled 1.0.3 - still same result
Seems the web app wants to access API on localhost (my laptop) rather than docker container (running on workstation)
![Screenshot 2023-04-23 alle 17 18 17](https://user-images.githubusercontent.com/18349597/233848284-7f66e0c8-693e-447f-bc7a-341176897052.jpg)

```
└─$ docker-compose up -d --build
Creating network "agent-llm_default" with the default driver
Pulling backend (ghcr.io/josh-xt/agent-llm-backend:v1.0.3)...
v1.0.3: Pulling from josh-xt/agent-llm-backend
9fbefa337077: Pull complete
a25702e0699e: Pull complete
adf6e8027509: Pull complete
a68430a46d9d: Pull complete
433875ea4139: Pull complete
5c52daab886f: Pull complete
cd31b324c5ff: Pull complete
fb4f0676a431: Pull complete
8451c92cc0d5: Pull complete
d447d1dc2f0a: Pull complete
f8d278489d72: Pull complete
3d2d781cb87c: Pull complete
abd389a49a20: Pull complete
9975274a1cfa: Pull complete
ed3527081a1f: Pull complete
Digest: sha256:6447e85a8b7011e98f3f8151de0c450f71869e5bf4b598bb2cbd18513021eca0
Status: Downloaded newer image for ghcr.io/josh-xt/agent-llm-backend:v1.0.3
Pulling frontend (ghcr.io/josh-xt/agent-llm-frontend:v1.0.3)...
v1.0.3: Pulling from josh-xt/agent-llm-frontend
f56be85fc22e: Pull complete
8f665685b215: Pull complete
e5fca6c395a6: Pull complete
561cb69653d5: Pull complete
12ae9070d9f9: Pull complete
e7ec2c118cb9: Pull complete
185f470cfdf1: Pull complete
03eae95f5ed3: Pull complete
98a74c91cb93: Pull complete
Digest: sha256:db1eeaaee6dad37fb77fc41c5a9c423a10c9d49305eb87ccb4b35670f526d884
Status: Downloaded newer image for ghcr.io/josh-xt/agent-llm-frontend:v1.0.3
Creating agent-llm_backend_1 ... done
Creating agent-llm_frontend_1 ... done

```

**Comment by Senior-S** [comment]
> Create a file `frontend/.env.local` with something like:
> 
> ```
> NEXT_PUBLIC_API_URI=https://YOUR.DOMAIN:PORT
> ```
> 
> Then run `npm run build` in `frontend` directory.
@alexl83 Try with this solution.

**Comment by Josh-XT** [comment]
The latest commit has an update to the docker-compose file to fix this issue and allow you to customize your URL if the back end is on a different machine.

**Comment by alexl83** [comment]
Here what I did:

added frontend/.env.local --> NEXT_PUBLIC_API_URI=https://moppio.local:5000

then docker-compose up -d --build --> pulled 1.0.4

still same result

**Comment by Senior-S** [comment]
Add `API_URI=https://moppio.local:5000` too

**Comment by alexl83** [comment]
running without docker, built with npm - same result
There's something I'm missing but I cannot understand what :(

**Comment by alexl83** [comment]
UPDATE:
if I run with python/npm - backend listens on 127.0.0.1 and frontend on 0.0.0.0 --> connecting from laptopt won't reach backend
fule frontend/.env.local
```
      NEXT_PUBLIC_API_URI: http://moppio.local:5000
      API_URI: http://moppio.local:5000
```

Running with docker:

added to docker-compose.yml
```
    environment:
      NEXT_PUBLIC_API_URI: http://moppio.local:5000
      API_URI: http://moppio.local:5000
```

same issue
