### ISSUE TITLE
/api/agent/agent-llm/command error 500

### ISSUE THREAD

**Issue by Jimisayss** [Josh-XT/Agent-LLM#48]
500Undocumented | Error: INTERNAL SERVER ERRORResponse bodyDownload{   "message": "Internal Server Error" } Response headers access-control-allow-origin: *  connection: close  content-length: 37  content-type: application/json  date: Sun,23 Apr 2023 15:20:17 GMT  server: gunicorn

Sorry great work on this it's amazing what you have done. I'm sure I need to do something differently, but I cannot get the commands to load using the docker or the local.

**Comment by Josh-XT** [comment]
> 

I am not sure that the latest version will fix the issue for sure or not, but we're not using gunicorn anymore, so it may be resolved in the latest.

**Comment by Jimisayss** [comment]
The new pull worked! thank you
