### ISSUE TITLE
requirements for commands missing from requirments.txt

### ISSUE THREAD

**Issue by Electrofried** [Josh-XT/Agent-LLM#5]
The following requirements for commands seem to be missing from requirments.txt causing failure to run via docker.

beautifulsoup4
docker
PyGithub
duckduckgo_search
playsound
gtts
selenium
webdriver_manager

Adding these to the requirments.txt at least seems to get the docker image to boot.

**Comment by Josh-XT** [comment]
Updated those, thanks!
