### ISSUE TITLE
proposal/request: remote usage step by step guide

### ISSUE THREAD

**Issue by alexl83** [Josh-XT/Agent-LLM#56]
Hi Josh, Maintainers,
it would be great if you could document - "tutorialize" running backend/fronted containers from a machine, and accessing the web api from another one in the same network

As of now, it's impossible at least for me - and I'm really eager in trying your AgentLLM :)
Hope you can consider it

Thank you :)
Ale

**Comment by Josh-XT** [comment]
> Hi Josh, Maintainers, it would be great if you could document - "tutorialize" running backend/fronted containers from a machine, and accessing the web api from another one in the same network
> 
> As of now, it's impossible at least for me - and I'm really eager in trying your AgentLLM :) Hope you can consider it
> 
> Thank you :) Ale

Hello! Take a look at the new and improved README in the repository. I've added Jupyter notebooks with quick start guides for multiple providers today.
