### ISSUE TITLE
Current docker image fails to start frontend and backend seems to hang at first worker creation without sending request to oobabooga.

### ISSUE THREAD

**Issue by Electrofried** [Josh-XT/Agent-LLM#6]
Not exactly sure what is happening here. Need to do more testing in a non-docker environment. The localhost:5000 webpage returns a 'page not found' response from the container. Perhaps the page is hosted somewhere else like localhost:5000/public/ or something? 

I managed to get the main.py to fire off a request to my oobabooga install in a native windows venv, however because it was outside a docker instance it did not seem like the .env was getting loaded to the environment variables.

In docker (WSL2), it just hangs after downloading some files and starting a worker, without ever sending off a request to the oobabooga server. Perhaps (and there is a high probability here) I am doing something wrong? I have started a fresh build now but it takes an hour or two on my internet to download everything again. 

Let me know if there is any further info I can provide for testing, or something specific you want me to try. I should mention I am running in a WSL2 Ubuntu image via windows 10, using docker desktop.

**Comment by Josh-XT** [comment]
Yeah, I am going to add an environment variable to set the base endpoint later today to also fix issue #3 .  I haven't been able to test with ooba yet.  For some reason after one of their updates, I can't run it anymore because I run out of VRAM.  I just need to go find a different model to use to test but haven't yet.  I appreciate the assist on testing!

**Comment by Josh-XT** [comment]
Give it another try, the latest changes should have this resolved.

**Comment by Electrofried** [comment]
I just tried but unfortunately "docker compose up" now fails with the following:

```
 => CANCELED [internal] load metadata for docker.io/library/python:3.8-slim-buster                                                                           0.0s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: target stage nginx could not be found
```

I don't have much experience with docker so it is possible (highly likely) I have done something incorrectly.

**Comment by Josh-XT** [comment]
I just modified the docker-compose file to pull the image form Github so that you're not having to try to build it if it isn't building.  Github workflows builds it and hosts it in the repo https://github.com/Josh-XT/Agent-LLM/pkgs/container/agent-llm

If you pull latest changes and try `docker-compose up -d`, it may work now.

**Comment by Electrofried** [comment]
Yup, already running now.
Will let you know how it goes when done and close if all working.

Thanks so much for all your help!

**Comment by Josh-XT** [comment]
> 

Thank you as well. People testing this while I'm writing it really helps keep it on track and stable.

**Comment by Electrofried** [comment]
Seems it is not the image, but something to do with the first stage definition when using docker compose.

```
 => [internal] load build definition from Dockerfile                  0.1s
 => => transferring dockerfile: 524B                0.0s
 => [internal] load .dockerignore                                              0.1s
 => => transferring context: 2B                                                                                                       0.0s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: target stage nginx could not be found
```

If I use docker build, it works fine however obviously does not run both services when the image is started.

**Comment by Electrofried** [comment]
ChatGPT has told me that apparently the first stage "nginx" could not be found, and that it is not declared in the Dockerfile, causing the error. It has recomended that I change the Dockerfile to the following to resolve:

`# Install Flask app dependencies
FROM python:3.8-slim-buster AS base
WORKDIR /app
COPY requirements.txt ./
RUN apt-get update
RUN apt-get install -y --no-install-recommends git build-essential
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get remove -y git build-essential
RUN apt-get autoremove -y
RUN rm -rf /var/lib/apt/lists/*

# Build Nginx stage
FROM nginx:1.21.0-alpine AS nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=base /app /app
EXPOSE 80

# Run Flask app with Gunicorn
FROM base AS gunicorn
COPY . /app
EXPOSE 5000
CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]
`

I have very little idea what this would do or if it would break everything, but I am going to put my faith behind chatGPT and give it a shot!

**Comment by Josh-XT** [comment]
The front end part of the docker-compose was left over from before I switched it.

**Comment by Electrofried** [comment]
Ok, started again with clean clone from latest github.

New error now:

`Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "gunicorn": executable file not found in $PATH: unknown`

**Comment by Josh-XT** [comment]
Looks like it just wasn't set to use .env

**Comment by Electrofried** [comment]
I think it is to do with the Dockerfile
Specifically this part: 
```
# Run Flask app with Gunicorn
FROM base AS gunicorn
COPY . /app
EXPOSE 5000
CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]
```

As far as I can see there is no "gunicorn" included in requirements or ever installed as part of the setup so it fails.

**Comment by Josh-XT** [comment]
> I think it is to do with the Dockerfile Specifically this part:
> 
> ```
> # Run Flask app with Gunicorn
> FROM base AS gunicorn
> COPY . /app
> EXPOSE 5000
> CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]
> ```
> 
> As far as I can see there is no "gunicorn" included in requirements or ever installed as part of the setup so it fails.

The requirements are met at build time on GitHub for the docker container through the GitHub Workflow that I have set up. I know that I have to `sudo` my docker-compose command, maybe you need to run as admin in Windows? I am not sure.

If you're still getting errors, try this next time you run it
```
docker-compose up --always-pull
```

That will force it to pull the latest image from Github if it is on an old one.

**Comment by OverwriteDev** [comment]
> Ok, started again with clean clone from latest github.
> 
> New error now:
> 
> `Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "gunicorn": executable file not found in $PATH: unknown`

@Josh-XT Trying out the docker setup on Windows and getting this same error. Tried it with cmd as admin and with anaconda terminal as admin in a venv with the same result. Using the most up-to-date brach.

**Comment by Josh-XT** [comment]
I'll do some testing on windows with it tonight. I'd just run the front end and back end local for now
```
python app.py
cd frontend
npm install
npm start
```

**Comment by Josh-XT** [comment]
You can also try this:

```
docker run -it --pull always -p 8080:5000 --env-file=.env ghcr.io/josh-xt/agent-llm:main
```

**Comment by Electrofried** [comment]
Closed due to latest update and we all hate front ends. :)
