### ISSUE TITLE
There is more than one error it is not working at all screenshots are attached of the errors.

### ISSUE THREAD

**Issue by CRCODE22** [Josh-XT/Agent-LLM#70]
![3242341232131](https://user-images.githubusercontent.com/88407346/234127257-5e530f06-50cb-45f9-a5ea-30db71b9b482.jpg)
![345345234234123123432423](https://user-images.githubusercontent.com/88407346/234127261-9a299431-abbf-4238-9e5e-d4f2e323dfb8.jpg)
![4564534543234](https://user-images.githubusercontent.com/88407346/234127262-dfc499a6-89e2-4068-943c-13540567f209.jpg)
![dev](https://user-images.githubusercontent.com/88407346/234127265-1108e396-0f00-4a08-8568-85d4c54b0c7d.jpg)
[.env.txt](https://github.com/Josh-XT/Agent-LLM/files/11314984/default.env.txt)

**Comment by Josh-XT** [comment]
You'll need to copy your `.env` to the frontend folder as `.env.local` for running locally.

**Comment by CRCODE22** [comment]
Ok I will try that thank you.
