### ISSUE TITLE
Front end returning network error :

### ISSUE THREAD

**Issue by DIGist** [Josh-XT/Agent-LLM#71]
Under the agent tab.
"Error!
Network Error"

agent-llm-backend-1   | INFO:     Started server process [1]
agent-llm-backend-1   | INFO:     Waiting for application startup.
agent-llm-backend-1   | INFO:     Application startup complete.
agent-llm-backend-1   | INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
agent-llm-frontend-1  | yarn run v1.22.19
agent-llm-frontend-1  | $ next start
agent-llm-frontend-1  | ready - started server on 0.0.0.0:3000, url: http://localhost:3000

**Comment by DIGist** [comment]
So here's what the network tab shows in dev tools:

![image](https://user-images.githubusercontent.com/81390274/234148526-9f63179a-9569-421f-8c4d-e17ef977cc24.png)


I'm going to continue to try to troubleshoot, but maybe the problem is I'm running the container on a server on my lan.. It doesn't seem to be picking up the environment variable from the docker-compose file.

**Comment by gururise** [comment]
Same problem here when trying to use BARD

**Comment by Josh-XT** [comment]
Hey folks! We've just made some major changes that should help fix a lot of these sort of issues. Please pull the latest and report back if you're still having these issues.

**Comment by DIGist** [comment]
Hi again,

Appreciate all the hard work. So It looks like the docker-compose.yml hasn't been updated to the newest version yet. I did that and ran docker compose again. While I have more menus in the frontend than I did previous, It would still appear something is amiss, I'm still getting the same Network error under providers and other items.

`(base) [user@brainbox Agent-LLM]$ docker exec -it 7d89 /bin/sh
/app # env
NODE_VERSION=14.21.3
HOSTNAME=7d892cd8c743
AI_MODEL=default
YARN_VERSION=1.22.19
SHLVL=1
HOME=/root
MODEL_PATH=/app/models/vicuna-13B-1.1-GPTQ-4bit-128g.GGML.bin
USE_MAC_OS_TTS=False
SELENIUM_WEB_BROWSER=chrome
AI_TEMPERATURE=0.2
TERM=xterm
OBJECTIVE=Write a PDF to Epub converter
AI_PROVIDER=llamacpp
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
USE_BRIAN_TTS=True
NO_MEMORY=False
INITIAL_TASK=Develop an initial task list.
NEXT_PUBLIC_API_URI=http://backend:5000
COMMANDS_ENABLED=True
PWD=/app
USE_LONG_TERM_MEMORY_ONLY=False
WORKING_DIRECTORY=WORKSPACE
AGENT_NAME=Agent-LLM
MAX_TOKENS=2000`

![image](https://user-images.githubusercontent.com/81390274/234200795-a5bf91a7-5a40-4a43-aa1d-87d57aa7b36c.png)


As mentioned I'm trying to run the app on a server in my local network and connect from my laptop. The network console of the browser seems to indicate the frontend is trying to request something at localhost:5000 instead of the NEXT_PUBLIC_API_URI above.

![image](https://user-images.githubusercontent.com/81390274/234201288-8d398a85-c2bb-4854-9664-d847ee3e648e.png)


`(base) [user@brainbox Agent-LLM]$ cat docker-compose.yml
version: "3.8"
services:
  frontend:
    image: ghcr.io/josh-xt/agent-llm-frontend:v1.0.7
    ports:
      - "80:3000"
    environment:
      NEXT_PUBLIC_API_URI: http://backend:5000
    env_file:
      - .env
    depends_on:
      - backend
  backend:
    image: ghcr.io/josh-xt/agent-llm-backend:v1.0.7
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
       - /sharedmodels:/app/models`
