### ISSUE TITLE
model issue

### ISSUE THREAD

**Issue by gsgoldma** [Josh-XT/Agent-LLM#73]
First off on windows 10

I use this model in llama.cpp already so I know it works at least but I do get this error when trying to load it

(venv) (base) D:\Agent-LLM>python app.py
←[32mINFO←[0m:     Started server process [←[36m8648←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://127.0.0.1:5000←[0m (Press CTRL+C to quit)
←[32mINFO←[0m:     127.0.0.1:51507 - "←[1mGET / HTTP/1.1←[0m" ←[31m404 Not Found←[0m
←[32mINFO←[0m:     127.0.0.1:51525 - "←[1mGET /api/agent HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:51525 - "←[1mGET /api/agent/Jeeves HTTP/1.1←[0m" ←[32m200 OK←[0m
INFO:     127.0.0.1:51525 - "GET /api/agent/Jeeves/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:51530 - "GET /api/agent HTTP/1.1" 200 OK
INFO:     127.0.0.1:51531 - "GET /api/agent/Jeeves HTTP/1.1" 200 OK
INFO:     127.0.0.1:51532 - "GET /api/agent/Jeeves/command HTTP/1.1" 200 OK
Using embedded DuckDB with persistence: data will be stored in: agents/default/memories
llama_model_load: loading model from 'D:\llama\models\ggml-vicuna-13b-1.1-q4_1.bin' - please wait ...
llama_model_load: n_vocab = 32000
llama_model_load: n_ctx   = 2000
llama_model_load: n_embd  = 5120
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 40
llama_model_load: n_layer = 40
llama_model_load: n_rot   = 128
llama_model_load: f16     = 5
llama_model_load: n_ff    = 13824
llama_model_load: n_parts = 2
llama_model_load: type    = 2
llama_model_load: invalid model file 'D:\llama\models\ggml-vicuna-13b-1.1-q4_1.bin' (bad f16 value 5)
llama_init_from_file: failed to load model
llama_generate: seed = 1682376819

when I try another model, I get a different error:

(venv) (base) D:\Agent-LLM>python app.py
←[32mINFO←[0m:     Started server process [←[36m10776←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://127.0.0.1:5000←[0m (Press CTRL+C to quit)
←[32mINFO←[0m:     127.0.0.1:51590 - "←[1mGET /api/agent HTTP/1.1←[0m" ←[32m200 OK←[0m
INFO:     127.0.0.1:51591 - "GET /api/agent/Jeeves/command HTTP/1.1" 200 OK
INFO:     127.0.0.1:51592 - "GET /api/agent/Jeeves HTTP/1.1" 200 OK
Using embedded DuckDB with persistence: data will be stored in: agents/default/memories
llama_model_load: loading model from 'D:\llama\models\ggml-alpaca-7b-q4.bin' - please wait ...
llama_model_load: invalid model file 'D:\llama\models\ggml-alpaca-7b-q4.bin' (too old, regenerate your model files or convert them with convert-unversioned-ggml-to-ggml.py!)
llama_init_from_file: failed to load model
llama_generate: seed = 1682377052

system_info: n_threads = 8 / 8 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |

**Comment by Josh-XT** [comment]
The error indicates that your model is too old and that you need to regenerate your model files or convert them with convert-unversioned-ggml-to-ggml.py.

**Comment by gsgoldma** [comment]
thank you.
 I'm not sure how to do that, but I did get it running with a different version of vicuna 13b. It works but t it mainly just repeated the instructions I gave it.

**Comment by Josh-XT** [comment]
> thank you. I'm not sure how to do that, but I did get it running with a different version of vicuna 13b. It works but t it mainly just repeated the instructions I gave it.

Most of that will be playing with the prompts in the model-prompts folders for whichever model you want to set it to work with. You can create your own prompts with text files in a new model folder you make as well. 

The prompt engineering done in most of our prompts were intended for use with OpenAI GPT3.5 and they work extremely well with that model and GPT4, but they're extremely verbose prompts that need to be in order to make the very large models do specific tasks. There are a lot less apologies and things to deal with "over riding" through prompting in the smaller models. You can likely get away with accomplishing the same thing through vastly reduced prompting.
