### ISSUE TITLE
Provider: Unable to connect to Oobabooga

### ISSUE THREAD

**Issue by CRCODE22** [Josh-XT/Agent-LLM#77]
Connection refused when trying to use Agent-LLM with oobabooga

env file important parts:

# =========================
# AI PROVIDER CONFIG
# =========================
AI_PROVIDER=oobabooga
AI_MODEL=vicuna
AI_TEMPERATURE=0.2
MAX_TOKENS=2000

# AI PROVIDER: CUSTOM (e.g., Oobabooga, Fastchat, etc.)
# =========================
AI_PROVIDER_URI=http://127.0.0.1:7860

Command to start Oobabooga:

call python server.py --model MiniGPT-4-LLaMA-13b-4bit-128g --listen --wbits 4 --groupsize 128 --auto-devices --no-stream

**Comment by Josh-XT** [comment]
Are you running Agent-LLM in Docker or local?
