### ISSUE TITLE
Network Error When Running From Docker Containers

### ISSUE THREAD

**Issue by gururise** [Josh-XT/Agent-LLM#79]
Running provider in Docker container using OpenAI API Key.  Using 1.0.7

![image](https://user-images.githubusercontent.com/4380009/234183418-d4d2f3b8-f779-41de-a3de-f77b0bf5624d.png)

**Comment by Josh-XT** [comment]
Click the 3 lines then agents. I am not sure why the front page isn't loading. @JamesonRGrieve

**Comment by gururise** [comment]
> Click the 3 lines then agents. I am not sure why the front page isn't loading. @JamesonRGrieve

Clicking the hamburger menu results in the following:

![image](https://user-images.githubusercontent.com/4380009/234184217-6356a699-594f-40f5-b54a-0dfd765525f8.png)

**Comment by Josh-XT** [comment]
Try giving it less or no commands to see if it is still doing that

**Comment by hamishm456** [comment]
I found because the back end and front end are operating in different containers the localhost command didn't work. need to force the IP address of the backend, then it worked.

**Comment by gururise** [comment]
> I found because the back end and front end are operating in different containers the localhost command didn't work. need to force the IP address of the backend, then it worked.

How did you force IP address of the backend?

**Comment by gururise** [comment]
> I found because the back end and front end are operating in different containers the localhost command didn't work. need to force the IP address of the backend, then it worked.

@hamishm456 How did you force IP address of the backend?

**Comment by DamonianoStudios** [comment]
To solve the issue of it disconnecting I ran the following commands.

Instructions for fixing backend crash:

```
steps to fix:
1. run the docker compose as instructed
2. open a new shell and run 'docker exec -it my-container-name bash'
3. in the container bash run
     a. apt-get update
     b. apt-get install g++
     c. pip install --force-reinstall --no-cache-dir hnswlib
4. 'exit'
5. run 'docker commit my-container-name my-new-image-name'
6. change the docker-compose.yaml file in the main directory:

backend:
    image: my-new-image-name
    ports:
      - "5000:5000"
    env_file:
      - .env
```

This worked for me, the "my-container-name" part is the sha:256 id of your container in docker
"my-image-name" can be whatever you choose

**Comment by hamishm456** [comment]
> I found because the back end and front end are operating in different containers the localhost command didn't work. need to force the IP address of the backend, then it worked.

make sure you have this in your copose 

> > I found because the back end and front end are operating in different containers the localhost command didn't work. need to force the IP address of the backend, then it worked.
> 
> @hamishm456 How did you force IP address of the backend?

I noticed the front end trying to connect to localhost:5000 using the developer tools.
I changed this line in the docker compose file to be the actual IP address of the host where the backend container is running.
  NEXT_PUBLIC_API_URI: http://<the actual location>:5000

**Comment by Josh-XT** [comment]
Dockerfile has been updated in v1.0.8, please let me know if that helps this issue.

**Comment by alexl83** [comment]
I just tried, same result - Network error
my docker-compose.yml

```
version: "3.8"
services:
  frontend:
    image: ghcr.io/josh-xt/agent-llm-frontend:v1.0.8
    ports:
      - "80:3000"
    environment:
      NEXT_PUBLIC_API_URI: ${NEXT_PUBLIC_API_URI:-http://moppio.local:5000}
    env_file:
      - .env
    depends_on:
      - backend
  backend:
    image: ghcr.io/josh-xt/agent-llm-backend:v1.0.8
    ports:
      - "5000:5000"
    env_file:
      - .env
```

**Comment by gururise** [comment]
1.0.8 results in the same error:
![image](https://user-images.githubusercontent.com/4380009/234377770-b6e80a4d-5aba-4dc8-84d4-229d24dc922a.png)

**Comment by r1di** [comment]
Having the same issue, commenting, so i get updated

**Comment by Josh-XT** [comment]
Please pull latest changes and see if issues are ongoing.

**Comment by gururise** [comment]
> Please pull latest changes and see if issues are ongoing.

Latest changes forces a build of the docker, but even so, still getting the same network error. Containers are not able to access each other.

**Comment by gitbute** [comment]
change Dockerfile-backend to this:
```dockerfile
EXPOSE 7437
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7437"]
```
then it works.

**Comment by Aopenz** [comment]
The network error is solved, but when I go to the third level menu, for example, I select chatgpt and it shows：ChatGPT；The content is empty.@gitbute

**Comment by r1di** [comment]
> The network error is solved, but when I go to the third level menu, for example, I select chatgpt and it shows：ChatGPT；The content is empty.@gitbute

Did you change anything else to use ChatGPT? Im still getting network error..

I changed the following lines in my .env, keeping the rest original:

AI_PROVIDER="chatgpt"
CHATGPT_USERNAME="emailInQoutes@mail.com"
CHATGPT_PASSWORD="passwordInQoutes"

Do I need to write the username and password in quotes?

**Comment by primecrypton** [comment]
Click the 3 lines then agents

**Comment by alexl83** [comment]
Still network error for me with latest git 12dac55eaf8461e5f44bd8def57afa049863b997

![Screenshot 2023-04-26 alle 13 23 07](https://user-images.githubusercontent.com/18349597/234560650-8f4e665d-a034-43f9-a632-f3afac2ad553.jpg)

Thank you for all the efforts in supporting us :)

**Comment by washieiko** [comment]
same for me, just pulled it 5 mins ago for the first time, only set openai api key and chatgpt username + pw

![openai](https://user-images.githubusercontent.com/95151804/234562598-3c1901c7-9d85-4de4-afcd-a7e9d182bc28.png)

**Comment by r1di** [comment]
i deleted everything cloned the repo new and used docker compose up -d.

It seems the problem is with the backend 

**agent-llm-backend-1   | INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)**

Everything was changed to port 7437, but somewhere in the code, i guess it still tries to run the server on port 5000?

**Comment by TroublesInParadise** [comment]
Same, ran a clean docker too, still getting 404'd on the page elements.

**Comment by TCS-mturpin** [comment]
@hemangjoshi37a that will do it as well thanks!

**Comment by washieiko** [comment]
not working for me, even with a fresh setup 
![aa4](https://user-images.githubusercontent.com/95151804/234616918-1e6ce1bc-39a7-4a53-9fff-509fef7634d3.png)
![aa1](https://user-images.githubusercontent.com/95151804/234616922-bb2b9ef8-b141-4e44-a5ba-2a15457a90f2.png)
![aa2](https://user-images.githubusercontent.com/95151804/234616924-3a761544-5af3-4aa8-bf5b-33cd5bee9ab7.png)
![aa3](https://user-images.githubusercontent.com/95151804/234616929-23954392-603c-435a-83e2-bea9fb12f2a9.png)

**Comment by r1di** [comment]
The moment i try to instruct the agent the backend crashes

I tried as a AI_PROVIDER openai and chatgpt, same result

The last two lines:
```

2023-04-26 17:18:12 INFO:     172.18.0.1:56584 - "OPTIONS /api/agent/TestGPT/task HTTP/1.1" 200 OK
2023-04-26 17:18:12 Using embedded DuckDB with persistence: data will be stored in: agents/TestGPT/memories
```

**Comment by OreoTango** [comment]
I am getting the Network Error as well. However, i believe the issue is due to the backend image file. When you run the 
docker history <image id>    (get that image id from your docker image related to the backend)
..you'll see:

CMD ["uvicorn" "app:app" "--host" "0.0.0.0" "--port" "5000"]

I had to rebuild the entire image using the newer dockerfile for backend.

docker build -t <your-new-backend-image> -f <your Dockerfile-backend>    (assuming you've updated the dockerfile with the right port now)

then get update docker-compose.yml to use the new backend image
and finally delete the container and rebuild again with:

docker-compose up --build -d

Naturally, you don't have to go through all these above, just wait till we have confirmation that the original docker image is updated, git pull everything again, delete your containers + backend image from docker and start again with:

docker-compose up --build -d

**Comment by tangseng110** [comment]
> I am still getting the Network Error as well despite starting from fresh git clone. However, i believe the issue is due to the backend image file. When you run:
> 
> docker history <image id> (get that image id from your docker image related to the backend)
> 
> ..you'll see:
> 
> CMD ["uvicorn" "app:app" "--host" "0.0.0.0" "--port" "5000"]
> 
> I had to rebuild the entire image using the newer dockerfile for backend.
> 
> docker build -t <your-new-backend-image> -f <your Dockerfile-backend> (assuming you've updated the dockerfile with the right port now)
> 
> then get update docker-compose.yml to use the new backend image. Finally delete the container and rebuild again with:
> 
> docker-compose up --build -d
> 
> Naturally, you don't have to go through all these above, just wait till we have confirmation that the original docker image is updated, git pull everything again, delete your containers + backend image from docker and start again with:
> 
> docker-compose up --build -d

After I followed the steps above, it still shows a network error

**Comment by JamesonRGrieve** [comment]
I'm currently running my development environment locally and not containerized so I'm not set up to replicate this. I'll have a go at that as soon as I'm able. In the meantime I'll mark this as help wanted if anyone wants to look into it and post their findings.

**Comment by OreoTango** [comment]
> 

1) Prior to rebuilding the new backend image file, did you update your "dockerfile-backend" file? for the last two lines of the file, find these and replace 0.0.0.0 with your host IP instead, eg 192.168.1.100   (find out your ip first)

EXPOSE 7437
#CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7437"]
CMD ["uvicorn", "app:app", "--host", "192.168.1.100", "--port", "7437"]

2) are you already replacing docker-compose.yml backend lines with these.... prior to rebuilding the containers again?

  backend:
    image: <your-new-be-image>
    init: true
    env_file:
      - .env
    ports:
      - "7437:7437"

**Comment by OreoTango** [comment]
> I'm currently running my development environment locally and not containerized so I'm not set up to replicate this. I'll have a go at that as soon as I'm able. In the meantime I'll mark this as help wanted if anyone wants to look into it and post their findings.

If Josh is able to rebuild the backend image with port 7437 for using uvicorn instead of 5000 and repost it, that would resolve the issue, since oobabooga API port is clashing on 5000.

**Comment by TroublesInParadise** [comment]
I'm still unable to get it running even after a clean re-cloning and removing/recomposing docker. Should I worry?

**Comment by Josh-XT** [comment]
> > I'm currently running my development environment locally and not containerized so I'm not set up to replicate this. I'll have a go at that as soon as I'm able. In the meantime I'll mark this as help wanted if anyone wants to look into it and post their findings.
> 
> If Josh is able to rebuild the backend image with port 7437 for using uvicorn instead of 5000 and repost it, that would resolve the issue, since oobabooga API port is clashing on 5000.

I believe all instances of port 5000 have been removes.  Are you still having this issue?

**Comment by zenchantlive** [comment]
> So, not saying this a perfect fix, but I spent days trying to figure out why the ENV variable wasn't being used in overriding localhost on the front end so I could access the frontend remotely over the network.
Here's my temporary workaround, build a modified frontend container. Makesure to update "REPLACEHEREWITHNETWORKRESOLVEABLENAMEORIP" with a hostname or IP that is resolveable on your network and in your containers. dockerfile for frontend:
FROM ghcr.io/josh-xt/agent-llm-frontend
WORKDIR /app
RUN find /app/.next/static/chunks/pages -type f -name "*.js" -exec grep -l 'http://localhost:7437/' {} ; | xargs -I {} sed -i 's|[http://localhost:7437|http://REPLACEHEREWITHNETWORKRESOLVEABLENAMEORIP:7437|g](http://localhost:7437%7Chttp//REPLACEHEREWITHNETWORKRESOLVEABLENAMEORIP:7437%7Cg)' {}
EXPOSE 3000
CMD ["yarn", "start"]
Then update your docker-compose to use the newly built frontend image.

This did not resolve the issue for me. I am still getting network errors on every page of localhost. 
It is not clear if I am replacing something or if i am adding to frontend

**Comment by TroublesInParadise** [comment]
> > > I'm currently running my development environment locally and not containerized so I'm not set up to replicate this. I'll have a go at that as soon as I'm able. In the meantime I'll mark this as help wanted if anyone wants to look into it and post their findings.
> > 
> > 
> > If Josh is able to rebuild the backend image with port 7437 for using uvicorn instead of 5000 and repost it, that would resolve the issue, since oobabooga API port is clashing on 5000.
> 
> I believe all instances of port 5000 have been removed. Are you still having this issue?

I've done another fresh reinstall. tried running both via docker and outside. There's still a port 5000 somewhere?
![image](https://user-images.githubusercontent.com/131233096/235300084-1a599cff-2293-4734-b043-0c015abb531f.png)

**Comment by Josh-XT** [comment]
I updated the docker-compose file. I think you're also still on an older version. After you pull the latest changes on the repo, try to do this:

```
docker-compose up --build -d
```

**Comment by TroublesInParadise** [comment]
> I updated the docker-compose file. I think you're also still on an older version. After you pull the latest changes on the repo, try to do this:
> 
> ```
> docker-compose up --build -d
> ```

Yes! Can confirm it works. It took a really long time to build and I'm not sure why, but everything loads as normal. Thank you!

**Comment by Josh-XT** [comment]
> > I updated the docker-compose file. I think you're also still on an older version. After you pull the latest changes on the repo, try to do this:
> > ```
> > docker-compose up --build -d
> > ```
> 
> Yes! Can confirm it works. It took a really long time to build and I'm not sure why, but everything loads as normal. Thank you!

Great news!

**Comment by alexl83** [comment]
still "Network Error" - backend points to localhost.

**Comment by Josh-XT** [comment]
> still "Network Error" - backend points to localhost.

Pull latest changes and run `docker-compose up --build -d`

**Comment by alexl83** [comment]
done, I changed the NEXT_PUBLIC_API_URI to my backend server
here's docker-compose.yml

```
version: "3.8"
services:
  frontend:
    build: ./frontend
    init: true
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_URI: ${NEXT_PUBLIC_API_URI:-http://moppio.local:7437}
    ports:
      - "80:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    init: true
    env_file:
      - .env
    ports:
      - "7437:7437"
    volumes:
      - ./data/agents:/app/agents:rw
      - ./data/workspace:/app/WORKSPACE:rw
      - ./models:/model:rw

```

![Screenshot 2023-04-29 alle 17 52 50](https://user-images.githubusercontent.com/18349597/235311672-7db3d84b-3cd7-4e78-baf5-3769652d804d.jpg)

**Comment by Josh-XT** [comment]
The docker compose file should remain as it is when you pull it from the repository. Your back end is not at the address you specified, so it can't find it and you're getting network errors. Backend is at http://backend:7437

**Comment by alexl83** [comment]
> The docker compose file should remain as it is when you pull it from the repository. Your back end is not at the address you specified, so it can't find it and you're getting network errors. Backend is at http://backend:7437

ok, rectified:
![Screenshot 2023-04-29 alle 17 57 19](https://user-images.githubusercontent.com/18349597/235311850-2a7791c5-ac98-4573-bf4c-043ddf104c1f.jpg)

my backend is not on the laptop I'm using to browse frontend, it's at http://192.168.1.138:7437

Backend+frontend==http://192.168.1.138
browser==192.168.1.132

**Comment by alexl83** [comment]
It works if I add an ".env.local" in fronted/ declaring NEXT_PUBLIC_API_URI=http://moppio.local:7437
Seems that variable passed from docker-compose.yml is not considered

**Comment by 23andreas** [comment]
> It works if I add an ".env.local" in fronted/ declaring NEXT_PUBLIC_API_URI=http://moppio.local:7437 Seems that variable passed from docker-compose.yml is not considered

I think what you're experiencing is more related to #114

**Comment by alexl83** [comment]
YEs, I agree! Thanks you

**Comment by tdimino** [comment]
I'm also receiving the "Error! Request failed with status code 404" on every page of the front-end I visit. 

Were we supposed to manually update line 10 in our "docker-compose-mac.yml" before we built our Docker container, or after? And silly as this question may be, where would we find the correct address needed here?
