### ISSUE TITLE
chromadb: AttributeError: 'NoneType' object has no attribute 'info'

### ISSUE THREAD

**Issue by VRImage** [Josh-XT/Agent-LLM#81]
When running Agent-LLM.py the following error appears:

Using embedded DuckDB with persistence: data will be stored in: agents/default/memories
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\Garlen\Agent-LLM\AgentLLM.py:299 in <module>                                            │
│                                                                                                  │
│   296 │                                                                                          │
│   297 │   # Run AgentLLM                                                                         │
│   298 │   agent = AgentLLM()                                                                     │
│ ❱ 299 │   agent.run(task=prompt, max_context_tokens=max_context_tokens, long_term_access=long_   │
│   300                                                                                            │
│                                                                                                  │
│ C:\Users\Garlen\Agent-LLM\AgentLLM.py:74 in run                                                  │
│                                                                                                  │
│    71 │   │   │   prompt = self.get_prompt_with_context(task=task, context=context)              │
│    72 │   │   else:                                                                              │
│    73 │   │   │   prompt = task                                                                  │
│ ❱  74 │   │   self.response = self.instruct(prompt)                                              │
│    75 │   │   if self.CFG.NO_MEMORY:                                                             │
│    76 │   │   │   self.store_result(task, self.response)                                         │
│    77 │   │   │   self.CFG.log_interaction(self.agent_name, self.response)                       │
│                                                                                                  │
│ C:\Users\Garlen\Agent-LLM\provider\oobabooga.py:21 in instruct                                   │
│                                                                                                  │
│   18 │   │   │   'truncation_length': 4096, 'ban_eos_token': False                               │
│   19 │   │   }                                                                                   │
│   20 │   │   response = requests.post(f"{CFG.AI_PROVIDER_URI}/run/textgen", json={"data": [js    │
│ ❱ 21 │   │   stripped_string = re.sub(r"(?<!\\)\\(?!n)", "", response.json()['data'][0])         │
│   22 │   │   return stripped_string                                                              │
│   23                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'data'
Exception ignored in: <function PersistentDuckDB.__del__ at 0x00000295EC2D93A0>
Traceback (most recent call last):
  File "C:\Users\Garlen\AppData\Local\Programs\Python\Python311\Lib\site-packages\chromadb\db\duckdb.py", line 445, in __del__
AttributeError: 'NoneType' object has no attribute 'info'

**Comment by Josh-XT** [comment]
Should be updated in #84 now, please pull latest changes to test again.
