### ISSUE TITLE
Agent keep changing task list and loop itself

### ISSUE THREAD

**Issue by Dojimanoryyu** [Josh-XT/Agent-LLM#86]
Agent seems keep changing the task list and loop itself instead of focusing on the first developed task (API Provider Open AI). Attached txt log.
[write 500 word news about twitter until today in txt file.txt](https://github.com/Josh-XT/Agent-LLM/files/11322771/write.500.word.news.about.twitter.until.today.in.txt.file.txt)

**Comment by Josh-XT** [comment]
Please update to v1.0.8, I believe this issue was resolved in #87
