### ISSUE TITLE
Suggestion: New provider - HuggingChat

### ISSUE THREAD

**Issue by TroublesInParadise** [Josh-XT/Agent-LLM#91]
https://huggingface.co/chat/
Runs on OpenAssistant. Would it be possible to integrate this somehow, or is it too early to say?

**Comment by Josh-XT** [comment]
> TroublesInParadise

Might be too early to tell.  I don't see any plugins or projects available yet to integrate with it.

**Comment by Josh-XT** [comment]
I'm going to close this one to table it for now until there is a module that exists for interfacing with it.   Thanks for bringing it up!  I'll be on the lookout and hopefully someone can inform me if it does come out either here or Discord.  

As soon as there is an ability to integrate with any provider by API or a Python module, I'm ready to add them.

**Comment by Josh-XT** [comment]
Added Huggingchat provider #149
